# Generated by Django 2.0.6 on 2018-08-03 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20180803_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='resourceattributetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='resourcetype',
            options={'ordering': ['name']},
        ),
    ]
