sch_abbrv: dict = {
    "Arts & Science": "ARTS",
    "College of Dentistry": "DEN",
    "Courant Institute of Mathematical Sciences": "CIMS",
    "Gallatin School of Individualized Study": "GAL",
    "Grossman School of Medicine": "MED",
    "NYU Long Island School of Medicine": "LIMED",
    "The Institute of Fine Arts": "IFA",
    "Institute for the Study of the Ancient World": "ISAW",
    "Leonard N. Stern School of Business": "STERN",
    "Robert F. Wagner Graduate School of Public Service": "WAG",
    "Rory Meyers College of Nursing": "MEYERS",
    "School of Global Public Health": "GPH",
    "School of Professional Studies": "SPS",
    "School of Law": "LAW",
    "Silver School of Social Work": "SSSW",
    "Steinhardt School of Culture, Education, and Human Development": "STEINHARDT",
    "Tandon School of Engineering": "TANDON",
    "Tisch School of the Arts": "TSOA",
    "NYU Abu Dhabi": "NYUAD",
    "NYU Shanghai": "NYUSH",
    "NYU IT": "NYUIT",
    "Center for Data Science": "CDS",
}
