# Generated by Django 4.2.23 on 2025-09-16 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "html_classes",
                    models.CharField(
                        blank=True,
                        help_text="Overriden by children. Meant for applying colors to tags. Bootstrap color docs: https://getbootstrap.com/docs/4.6/utilities/colors/",
                        max_length=255,
                        verbose_name="HTML classes",
                    ),
                ),
                (
                    "user_permissions",
                    models.CharField(
                        choices=[("none", "None"), ("view", "View"), ("edit", "Edit")],
                        default="none",
                        help_text="None: users cannot view, add, or remove this tag. View: users can only view this tag. Edit: users can view, add, or remove this tag.",
                        max_length=32,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "allowed_models",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Inherited by its children.",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "parent_tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tag.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalTag",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "html_classes",
                    models.CharField(
                        blank=True,
                        help_text="Overriden by children. Meant for applying colors to tags. Bootstrap color docs: https://getbootstrap.com/docs/4.6/utilities/colors/",
                        max_length=255,
                        verbose_name="HTML classes",
                    ),
                ),
                (
                    "user_permissions",
                    models.CharField(
                        choices=[("none", "None"), ("view", "View"), ("edit", "Edit")],
                        default="none",
                        help_text="None: users cannot view, add, or remove this tag. View: users can only view this tag. Edit: users can view, add, or remove this tag.",
                        max_length=32,
                    ),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_tag",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tag.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical tag",
                "verbose_name_plural": "historical tags",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
