from coldfront.config.base import INSTALLED_APPS
from coldfront.config.env import ENV

INSTALLED_APPS += [
    'coldfront.plugins.slate_project',
]

LDAP_SLATE_PROJECT_SERVER_URI = ENV.str('LDAP_SLATE_PROJECT_SERVER_URI')
LDAP_SLATE_PROJECT_BASE_DN = ENV.str('LDAP_SLATE_PROJECT_BASE_DN')
LDAP_SLATE_PROJECT_BIND_DN = ENV.str('LDAP_SLATE_PROJECT_BIND_DN')
LDAP_SLATE_PROJECT_BIND_PASSWORD = ENV.str('LDAP_SLATE_PROJECT_BIND_PASSWORD')
LDAP_SLATE_PROJECT_CONNECT_TIMEOUT = ENV.str('LDAP_SLATE_PROJECT_CONNECT_TIMEOUT', 2.5)
DISPLAY_USER_SLATE_PROJECTS = ENV.str('DISPLAY_USER_SLATE_PROJECTS', False)
SLATE_PROJECT_EMAIL = ENV.str('SLATE_PROJECT_EMAIL')

ENABLE_LDAP_SLATE_PROJECT_SYNCING = ENV.bool('ENABLE_LDAP_SLATE_PROJECT_SYNCING', False)
ENABLE_LDAP_ELIGIBILITY_SERVER = ENV.bool('ENABLE_LDAP_ELIGIBILITY_SERVER', False)
SLATE_PROJECT_ELIGIBILITY_ACCOUNT = ENV.str('SLATE_PROJECT_ELIGIBILITY_ACCOUNT')
SLATE_PROJECT_ACCOUNT = ENV.str('SLATE_PROJECT_ACCOUNT')
SLATE_PROJECT_SHOW_ESTIMATED_COST = ENV.str('SLATE_PROJECT_SHOW_ESTIMATED_COST', False)
SLATE_PROJECT_DIR = ENV.str('SLATE_PROJECT_DIR')
SLATE_PROJECT_INCOMING_DIR = ENV.str('SLATE_PROJECT_INCOMING_DIR')
SLATE_PROJECT_ALLOCATED_QUANTITY_THRESHOLD = ENV.int('SLATE_PROJECT_ALLOCATED_QUANTITY_THRESHOLD', 120)
if ENABLE_LDAP_ELIGIBILITY_SERVER:
    LDAP_ELIGIBILITY_SERVER_URI = ENV.str('LDAP_ELIGIBILITY_SERVER_URI')
    LDAP_ELIGIBILITY_BASE_DN = ENV.str('LDAP_ELIGIBILITY_BASE_DN')
    LDAP_ELIGIBILITY_BIND_DN = ENV.str('LDAP_ELIGIBILITY_BIND_DN')
    LDAP_ELIGIBILITY_BIND_PASSWORD = ENV.str('LDAP_ELIGIBILITY_BIND_PASSWORD')
    LDAP_ELIGIBILITY_CONNECT_TIMEOUT = ENV.str('LDAP_ELIGIBILITY_CONNECT_TIMEOUT', 2.5)
    LDAP_ADS_NETID_FORMAT = ENV.str('LDAP_ADS_NETID_FORMAT')
