from coldfront.config.base import INSTALLED_APPS
from coldfront.config.env import ENV

INSTALLED_APPS += [
    'coldfront.plugins.slate_project',
]

LDAP_SLATE_PROJECT_SERVER_URI = ENV.str('LDAP_SLATE_PROJECT_SERVER_URI')
LDAP_SLATE_PROJECT_BASE_DN = ENV.str('LDAP_SLATE_PROJECT_BASE_DN')
LDAP_SLATE_PROJECT_BIND_DN = ENV.str('LDAP_SLATE_PROJECT_BIND_DN')
LDAP_SLATE_PROJECT_BIND_PASSWORD = ENV.str('LDAP_SLATE_PROJECT_BIND_PASSWORD')
LDAP_SLATE_PROJECT_CONNECT_TIMEOUT = ENV.str('LDAP_SLATE_PROJECT_CONNECT_TIMEOUT', 2.5)
DISPLAY_USER_SLATE_PROJECTS = ENV.str('DISPLAY_USER_SLATE_PROJECTS', False)
SLATE_PROJECT_EMAIL = ENV.str('SLATE_PROJECT_EMAIL')

ENABLE_LDAP_ELIGIBILITY_SERVER = ENV.bool('ENABLE_LDAP_ELIGIBILITY_SERVER', False)
if ENABLE_LDAP_ELIGIBILITY_SERVER:
    LDAP_ELIGIBILITY_SERVER_URI = ENV.str('LDAP_ELIGIBILITY_SERVER_URI')
    LDAP_ELIGIBILITY_BASE_DN = ENV.str('LDAP_ELIGIBILITY_BASE_DN')
    LDAP_ELIGIBILITY_BIND_DN = ENV.str('LDAP_ELIGIBILITY_BIND_DN')
    LDAP_ELIGIBILITY_BIND_PASSWORD = ENV.str('LDAP_ELIGIBILITY_BIND_PASSWORD')
    LDAP_ELIGIBILITY_CONNECT_TIMEOUT = ENV.str('LDAP_ELIGIBILITY_CONNECT_TIMEOUT', 2.5)