from coldfront.config.base import INSTALLED_APPS
from coldfront.config.env import ENV

INSTALLED_APPS += [
    'coldfront.plugins.system_monitor'
]

SYSTEM_MONITOR_PANEL_TITLE = ENV.str('COLDFRONT_PLUGIN_SYSMON_TITLE', default='HPC Cluster Status')
SYSTEM_MONITOR_ENDPOINT = ENV.str('COLDFRONT_PLUGIN_SYSMON_ENDPOINT')
SYSTEM_MONITOR_DISPLAY_MORE_STATUS_INFO_LINK = ENV.str('COLDFRONT_PLUGIN_SYSMON_LINK')
SYSTEM_MONITOR_DISPLAY_XDMOD_LINK = ENV.str('COLDFRONT_PLUGIN_SYSMON_XDMOD_LINK')

