# Generated by Django 2.1.7 on 2019-03-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['end_date'], 'permissions': (('can_view_all_subscriptions', 'Can view all subscriptions'), ('can_review_subscription_requests', 'Can review subscription requests'))},
        ),
        migrations.AddField(
            model_name='subscriptionusermessage',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
