# Generated by Django 2.1.1 on 2018-09-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['active_until'], 'permissions': (('can_view_all_subscriptions', 'Can view all subscriptions'), ('can_review_subscription_requests', 'Can review subscription requests'))},
        ),
    ]
