# Generated by Django 2.1.2 on 2018-11-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20180914_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['pk']},
        ),
        migrations.RenameField(
            model_name='historicalsubscription',
            old_name='active_until',
            new_name='end_until',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='active_until',
            new_name='end_until',
        ),
    ]
