# Generated by Django 2.1.2 on 2018-12-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20181101_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscription',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
