# Generated by Django 2.1.2 on 2018-12-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_auto_20181207_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubscriptionattribute',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='subscriptionattribute',
            name='is_private',
        ),
        migrations.AddField(
            model_name='historicalsubscriptionattributetype',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionattributetype',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
