# Builder Image
FROM python:3.9-slim-bullseye as builder

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        default-libmysqlclient-dev \
        libpq-dev \
        git \
        pkg-config && \
    apt-get clean -y

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

WORKDIR /opt
COPY . .
RUN pip3 install -r ./requirements.txt
RUN python setup.py build
RUN python setup.py install
RUN pip3 install ./



# Final Image
FROM python:3.9-slim-bullseye

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        netcat libmariadb3 mycli libpq5 && \
    apt-get clean -y

COPY --from=builder --chown=1001:0 /opt /opt


COPY entrypoint.sh /opt/venv/bin

ENV PATH="/opt/venv/bin:$PATH"
ENV DJANGO_SETTINGS_MODULE="coldfront.config.database"

EXPOSE 8000

USER 1001

CMD [ "entrypoint.sh" ]