version = 1
SPDX-PackageName = "coldfront"
SPDX-PackageDownloadLocation = "https://github.com/ubccr/coldfront"

[[annotations]]
path = [
    ".python-version",
    "Dockerfile",
    ".dockerignore",
    ".env.testing",
    "MANIFEST.in",
    "pyproject.toml",
    "zensical.toml",
    "**.yaml",
    "**.yml",
    "**.md",
    "**.txt",
    "**.csv",
    "**.sql",
    "**.gitignore",
    "**.html",
    "**.css",
    "**.scss",
    "**.js",
    "**.po",
    "**.mo",
    "**.webmanifest",
]
SPDX-FileCopyrightText = "(C) University at Buffalo"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "docs/assets/**",
    "**.ico",
]
SPDX-FileCopyrightText = "(C) University at Buffalo"
SPDX-License-Identifier = "CC-BY-NC-ND-4.0"

[[annotations]]
path = [
    "NOTICE",
    "uv.lock",
    "src/coldfront/static/package-lock.json",
    "src/coldfront/static/bundles/manifest.json",
    "src/coldfront/static/package.json",
    "src/coldfront/static/tsconfig.json",
    "src/coldfront/static/.prettierignore",
    "src/coldfront/static/.prettierrc",
    "src/coldfront/**.png",
    "src/coldfront/**.jpg",
    "tests/slurm/conf/*.conf",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "src/coldfront/static/bundles/fa-*.woff2",
]
SPDX-FileCopyrightText = "Copyright (c) 2011-2025 The Bootstrap Authors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "tests/slurm/specs/openapi_spec*",
]
SPDX-FileCopyrightText = "Copyright (C) SchedMD LLC"
SPDX-License-Identifier = "GPL-2.0-or-later"
