# SPDX-FileCopyrightText: (C) University at Buffalo
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.6 on 2026-08-04 00:25

import django.db.models.deletion
import django.db.models.functions.text
import mptt.fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0002_initial"),
        ("ras", "0001_initial"),
        ("tenancy", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_allocations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="resource_object_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="allocations", to="contenttypes.contenttype"
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="core.TaggedItem",
                to="core.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="allocationchangerequest",
            name="allocation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="change_requests",
                to="ras.allocation",
                verbose_name="allocation",
            ),
        ),
        migrations.AddField(
            model_name="allocationchangerequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requested_allocation_changes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="requested by",
            ),
        ),
        migrations.AddField(
            model_name="allocationchangerequest",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviewed_allocation_changes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="reviewer",
            ),
        ),
        migrations.AddField(
            model_name="allocationchangerequest",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="core.TaggedItem",
                to="core.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="The Group associated with this project. Users added to the project are automatically added to this group.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="users.group",
                verbose_name="group",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="owned_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="core.TaggedItem",
                to="core.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="allocations", to="ras.project"
            ),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="users", to="ras.project"
            ),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="core.TaggedItem",
                to="core.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="projects", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="ras.resource",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="core.TaggedItem",
                to="core.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resources",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="resourcetype",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="core.TaggedItem",
                to="core.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="resource_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resources",
                to="ras.resourcetype",
            ),
        ),
        migrations.AddIndex(
            model_name="allocation",
            index=models.Index(
                fields=["resource_object_type", "resource_object_id"], name="ras_allocat_resourc_ca8a1d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectuser",
            unique_together={("user", "project")},
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("parent"),
                models.F("tenant"),
                name="ras_resource_unique_name_parent_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("parent"),
                condition=models.Q(("tenant__isnull", True)),
                name="ras_resource_unique_name_parent",
                violation_error_message="Resource name must be unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True), ("tenant__isnull", True)),
                fields=("name",),
                name="ras_resource_name",
                violation_error_message="A top-level resource with this name already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.UniqueConstraint(fields=("parent", "slug"), name="ras_resource_parent_slug"),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("slug",),
                name="ras_resource_slug",
                violation_error_message="A top-level resource with this slug already exists.",
            ),
        ),
    ]
