# SPDX-FileCopyrightText: (C) University at Buffalo
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.7 on 2026-08-17 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import coldfront.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ras", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectInvite",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                ("email", models.EmailField(max_length=254, verbose_name="email address")),
                (
                    "code_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 digest of the one-time invite token. Auto-generated on creation.",
                        max_length=64,
                        unique=True,
                        verbose_name="invite code",
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True, verbose_name="accepted")),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="invites", to="ras.project"
                    ),
                ),
            ],
            options={
                "verbose_name": "project invite",
                "verbose_name_plural": "project invites",
                "ordering": ["created"],
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
    ]
