# Generated by Django 3.2.13 on 2022-07-21 16:02

import coldfront.core.utils.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTypeChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title'], 'permissions': (('can_view_all_projects', 'Can view all projects'), ('can_review_pending_projects', 'Can review pending project requests/reviews'))},
        ),
        migrations.RenameField(
            model_name='historicalprojectreview',
            old_name='reason_for_not_updating_project',
            new_name='project_updates',
        ),
        migrations.RenameField(
            model_name='projectreview',
            old_name='reason_for_not_updating_project',
            new_name='project_updates',
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='max_managers',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='pi_username',
            field=models.CharField(blank=True, help_text='Required if you will not be the PI of this project. Graduate students cannot be the PI', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='private',
            field=models.BooleanField(default=False, help_text='A private project will not show up in the PI search results if someone searchs for you/your PI.'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='requestor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='slurm_account_name',
            field=models.CharField(blank=True, help_text='\nThis is only required if you need a resource that uses Slurm. The name must be at least three\ncharacters long and cannot contain numbers or special characters. Once set it cannot be changed.\n        ', max_length=15, validators=[django.core.validators.MinLengthValidator(3, 'The slurm account name must be at least 3 characters'), coldfront.core.utils.validators.IsAlpha('The slurm account name must not contain numbers of special characters')]),
        ),
        migrations.AddField(
            model_name='historicalprojectreview',
            name='allocation_renewals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='max_managers',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='pi_username',
            field=models.CharField(blank=True, help_text='Required if you will not be the PI of this project. Graduate students cannot be the PI', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='private',
            field=models.BooleanField(default=False, help_text='A private project will not show up in the PI search results if someone searchs for you/your PI.'),
        ),
        migrations.AddField(
            model_name='project',
            name='requestor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requestor_user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slurm_account_name',
            field=models.CharField(blank=True, help_text='\nThis is only required if you need a resource that uses Slurm. The name must be at least three\ncharacters long and cannot contain numbers or special characters. Once set it cannot be changed.\n        ', max_length=15, validators=[django.core.validators.MinLengthValidator(3, 'The slurm account name must be at least 3 characters'), coldfront.core.utils.validators.IsAlpha('The slurm account name must not contain numbers of special characters')]),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='allocation_renewals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='This cannot be changed once your project is submitted.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.projecttypechoice'),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ForeignKey(default=1, help_text='This cannot be changed once your project is submitted.', on_delete=django.db.models.deletion.CASCADE, to='project.projecttypechoice'),
            preserve_default=False,
        ),
    ]
