# Generated by Django 2.2.24 on 2021-10-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='projects', to='organization.Organization'),
        ),
    ]
