# Generated by Django 2.2.13 on 2021-03-07 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='usage',
        ),
    ]
