# Generated by Django 4.2.11 on 2025-02-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="slurm_account_names",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="project",
            name="slurm_account_names",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
