# Generated by Django 3.2.13 on 2022-07-01 14:40

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectreviewstatuschoice',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
        migrations.AlterModelOptions(
            name='projectstatuschoice',
            options={'ordering': (django.db.models.functions.text.Lower('name'),)},
        ),
        migrations.AlterModelOptions(
            name='projectuserrolechoice',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
        migrations.AlterModelOptions(
            name='projectuserstatuschoice',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
