# Generated by Django 2.2.18 on 2022-06-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectusermessage_is_private'),
        ('project', '0002_remove_projectuser_usage'),
    ]

    operations = [
    ]
