# Generated by Django 3.2.14 on 2022-08-29 13:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20220721_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectusermessage',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='description',
            field=models.TextField(default='', help_text='\nPlease provide a brief description or abstract about your project including any applications or\nworkflows you intend to use, and how you primarily intend to use the system, including if PHI will\nbe stored. Please include your area of research and your department. If this is for a class please\nput the approximate class size.\n', validators=[django.core.validators.MinLengthValidator(10, 'The project description must be > 10 characters.')]),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='pi_username',
            field=models.CharField(blank=True, help_text='Required if you will not be the PI of this project. Only faculty and staff can be the PI', max_length=20, verbose_name='PI Username'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='slurm_account_name',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='This cannot be changed once your project is submitted. Class projects expire at the end of every semester. Research projects expire once a year.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.projecttypechoice'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', help_text='\nPlease provide a brief description or abstract about your project including any applications or\nworkflows you intend to use, and how you primarily intend to use the system, including if PHI will\nbe stored. Please include your area of research and your department. If this is for a class please\nput the approximate class size.\n', validators=[django.core.validators.MinLengthValidator(10, 'The project description must be > 10 characters.')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='pi_username',
            field=models.CharField(blank=True, help_text='Required if you will not be the PI of this project. Only faculty and staff can be the PI', max_length=20, verbose_name='PI Username'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slurm_account_name',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.ForeignKey(help_text='This cannot be changed once your project is submitted. Class projects expire at the end of every semester. Research projects expire once a year.', on_delete=django.db.models.deletion.CASCADE, to='project.projecttypechoice'),
        ),
    ]
