# Generated by Django 2.2.13 on 2020-11-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_add_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='pi',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pi',
        ),
    ]
