# Generated by Django 2.2.13 on 2020-12-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_pi_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='joins_require_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='joins_require_approval',
            field=models.BooleanField(default=False),
        ),
    ]
