# Generated by Django 3.2.14 on 2022-08-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectusermessage_is_private'),
        ('project', '0003_auto_20220519_0940'),
    ]

    operations = [
    ]
