# Generated by Django 3.2.14 on 2022-11-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectadminaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='pi_username',
            field=models.CharField(blank=True, help_text='\nRequired if you will not be the PI of this project. Only faculty and staff can be the PI. They are\nrequired to log onto the site at least once before they can be added.\n', max_length=20, verbose_name='PI Username'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pi_username',
            field=models.CharField(blank=True, help_text='\nRequired if you will not be the PI of this project. Only faculty and staff can be the PI. They are\nrequired to log onto the site at least once before they can be added.\n', max_length=20, verbose_name='PI Username'),
        ),
    ]
