# Generated by Django 3.2.13 on 2022-06-22 20:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_auto_20220621_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalProjectUserEmail',
            new_name='HistoricalProjectAddUserEmailTemplate',
        ),
        migrations.RenameModel(
            old_name='ProjectUserEmail',
            new_name='ProjectAddUserEmailTemplate',
        ),
        migrations.AlterModelOptions(
            name='historicalprojectadduseremailtemplate',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical project add user email template'},
        ),
    ]
