# Generated by Django 4.2.11 on 2025-01-24 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0004_auto_20230406_1133"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalproject",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical project",
                "verbose_name_plural": "historical projects",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalprojectattribute",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical project attribute",
                "verbose_name_plural": "historical project attributes",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalprojectattributetype",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical project attribute type",
                "verbose_name_plural": "historical project attribute types",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalprojectattributeusage",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical project attribute usage",
                "verbose_name_plural": "historical project attribute usages",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalprojectreview",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical project review",
                "verbose_name_plural": "historical project reviews",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalprojectuser",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical project user",
                "verbose_name_plural": "historical Project User Status",
            },
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="field_of_science",
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="school",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="school.school",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.school",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalprojectattribute",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalprojectattributetype",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalprojectattributeusage",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalprojectreview",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalprojectuser",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("title", "pi")},
        ),
        migrations.RemoveField(
            model_name="project",
            name="field_of_science",
        ),
    ]
