# Generated by Django 3.2.17 on 2023-05-15 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_merge_20220623_1111'),
        ('project', '0004_auto_20230406_1133'),
    ]

    operations = [
    ]
