# Generated by Django 4.2.11 on 2025-01-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
        ("project", "0005_alter_historicalproject_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="school",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.school",
            ),
        ),
    ]
