# Generated by Django 3.2.13 on 2022-06-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20220622_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprojectadduseremailtemplate',
            name='bcc',
        ),
        migrations.RemoveField(
            model_name='projectadduseremailtemplate',
            name='bcc',
        ),
    ]
