# SPDX-FileCopyrightText: (C) ColdFront Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 4.2.11 on 2025-04-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_alter_historicalproject_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="institution",
            field=models.CharField(blank=True, default="None", max_length=80),
        ),
        migrations.AddField(
            model_name="project",
            name="institution",
            field=models.CharField(blank=True, default="None", max_length=80),
        ),
    ]
