# Generated by Django 3.1.7 on 2021-03-21 04:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_joins_require_approval_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUserJoinRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('project_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectuser')),
            ],
            options={
                'verbose_name': 'Project User Join Request',
                'verbose_name_plural': 'Project User Join Requests',
            },
        ),
    ]
