# Generated by Django 3.2.14 on 2024-01-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20230615_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectadminaction',
            name='action',
            field=models.CharField(max_length=100),
        ),
    ]
