# SPDX-FileCopyrightText: (C) ColdFront Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 4.2.23 on 2025-09-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0001_initial"),
        ("project", "0006_historicalproject_institution_project_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(blank=True, to="tag.tag"),
        ),
    ]
