# Generated by Django 3.2.13 on 2022-06-23 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20220622_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprojectadduseremailtemplate',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='ProjectAddUserEmailTemplate',
        ),
        migrations.DeleteModel(
            name='HistoricalProjectAddUserEmailTemplate',
        ),
    ]
