# Generated by Django 3.1.7 on 2021-03-28 19:34

import coldfront.core.project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_allocation_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsavioprojectallocationrequest',
            name='state',
            field=models.JSONField(default=coldfront.core.project.models.savio_project_request_state_schema),
        ),
        migrations.AddField(
            model_name='historicalvectorprojectallocationrequest',
            name='state',
            field=models.JSONField(default=coldfront.core.project.models.vector_project_request_state_schema),
        ),
        migrations.AddField(
            model_name='savioprojectallocationrequest',
            name='state',
            field=models.JSONField(default=coldfront.core.project.models.savio_project_request_state_schema),
        ),
        migrations.AddField(
            model_name='vectorprojectallocationrequest',
            name='state',
            field=models.JSONField(default=coldfront.core.project.models.vector_project_request_state_schema),
        ),
    ]
