# Generated by Django 4.2.11 on 2024-12-11 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_attributetype_projectattribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(db_collation='utf8mb4_0900_ai_ci', default='', help_text='\nPlease provide a brief description or abstract about your project including any applications or\nworkflows you intend to use, and how you primarily intend to use the system, including if PHI will\nbe stored. Please include your area of research and your department. If this is for a class please\nput the approximate class size.\n', validators=[django.core.validators.MinLengthValidator(10, 'The project description must be > 10 characters.')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=255),
        ),
    ]
