# Generated by Django 3.1.7 on 2021-05-03 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_project_allocation_request_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuserjoinrequest',
            name='reason',
            field=models.TextField(default='This is the default join reason.', validators=[django.core.validators.MinLengthValidator(20, 'The project join reason must be > 20 characters.')]),
        ),
    ]
