# Generated by Django 3.1.7 on 2021-05-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_projectuserjoinrequest_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsavioprojectallocationrequest',
            name='extra_fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='savioprojectallocationrequest',
            name='extra_fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicalsavioprojectallocationrequest',
            name='allocation_type',
            field=models.CharField(choices=[('FCA', 'Faculty Compute Allowance (FCA)'), ('CO', 'Condo Allocation'), ('PCA', 'Partner Compute Allowance (PCA)'), ('MOU', 'Memorandum of Use (MOU)')], max_length=16),
        ),
        migrations.AlterField(
            model_name='savioprojectallocationrequest',
            name='allocation_type',
            field=models.CharField(choices=[('FCA', 'Faculty Compute Allowance (FCA)'), ('CO', 'Condo Allocation'), ('PCA', 'Partner Compute Allowance (PCA)'), ('MOU', 'Memorandum of Use (MOU)')], max_length=16),
        ),
    ]
