# Generated by Django 3.1.7 on 2021-05-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_allocation_requests_mou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsavioprojectallocationrequest',
            name='allocation_type',
            field=models.CharField(choices=[('FCA', 'Faculty Compute Allowance (FCA)'), ('CO', 'Condo Allocation'), ('PCA', 'Partner Compute Allowance (PCA)'), ('MOU', 'Memorandum of Understanding (MOU)')], max_length=16),
        ),
        migrations.AlterField(
            model_name='savioprojectallocationrequest',
            name='allocation_type',
            field=models.CharField(choices=[('FCA', 'Faculty Compute Allowance (FCA)'), ('CO', 'Condo Allocation'), ('PCA', 'Partner Compute Allowance (PCA)'), ('MOU', 'Memorandum of Understanding (MOU)')], max_length=16),
        ),
    ]
