# Generated by Django 3.2.5 on 2021-09-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_project_allocation_requests_ica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsavioprojectallocationrequest',
            name='allocation_type',
            field=models.CharField(choices=[('FCA', 'Faculty Compute Allowance (FCA)'), ('CO', 'Condo Allocation'), ('ICA', 'Instructional Compute Allowance (ICA)'), ('PCA', 'Partner Compute Allowance (PCA)'), ('RECHARGE', 'Recharge Allocation')], max_length=16),
        ),
        migrations.AlterField(
            model_name='savioprojectallocationrequest',
            name='allocation_type',
            field=models.CharField(choices=[('FCA', 'Faculty Compute Allowance (FCA)'), ('CO', 'Condo Allocation'), ('ICA', 'Instructional Compute Allowance (ICA)'), ('PCA', 'Partner Compute Allowance (PCA)'), ('RECHARGE', 'Recharge Allocation')], max_length=16),
        ),
    ]
