# Generated by Django 3.2.5 on 2021-12-01 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_project_allocation_request_rename_mou_to_recharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='joins_auto_approval_delay',
        ),
        migrations.RemoveField(
            model_name='project',
            name='joins_auto_approval_delay',
        ),
    ]
