# Generated by Django 3.2.5 on 2022-03-16 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0007_allocationadditionrequest_allocationadditionrequeststatuschoice'),
        ('project', '0016_remove_auto_approvals'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsavioprojectallocationrequest',
            name='allocation_period',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='allocation.allocationperiod'),
        ),
        migrations.AddField(
            model_name='savioprojectallocationrequest',
            name='allocation_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocation_period', to='allocation.allocationperiod'),
        ),
    ]
