# Generated by Django 3.2.5 on 2022-03-21 20:23

from django.db import migrations, models
import django.utils.timezone


def add_times_to_existing_requests(apps, schema_editor):
    SavioProjectAllocationRequest = apps.get_model(
        'project', 'SavioProjectAllocationRequest')
    ProjectAllocationRequestStatusChoice = apps.get_model(
        'project', 'ProjectAllocationRequestStatusChoice')
    HistoricalSavioProjectAllocationRequest = apps.get_model(
        'project', 'HistoricalSavioProjectAllocationRequest')
    approved_processing_status = \
        ProjectAllocationRequestStatusChoice.objects.get(
            name='Approved - Processing')
    approved_complete_status = \
        ProjectAllocationRequestStatusChoice.objects.get(
            name='Approved - Complete')
    for request in SavioProjectAllocationRequest.objects.all():
        request.request_time = request.created
        # Set the approval_time to be the first datetime at which the object
        # had the 'Approved - Processing' status, if any.
        historical_objects_processed = \
            HistoricalSavioProjectAllocationRequest.objects.filter(
                id=request.id,
                status=approved_processing_status).order_by('history_date')
        if historical_objects_processed.exists():
            request.approval_time = \
                historical_objects_processed.first().history_date
        # Set the completion_time to be the first datetime at which the object
        # had the 'Approved - Complete' status, if any.
        historical_objects_complete = \
            HistoricalSavioProjectAllocationRequest.objects.filter(
                id=request.id,
                status=approved_complete_status).order_by('history_date')
        if historical_objects_complete.exists():
            request.completion_time = \
                historical_objects_complete.first().history_date
        request.save()


def nullify_times(apps, schema_editor):
    SavioProjectAllocationRequest = apps.get_model(
        'project', 'SavioProjectAllocationRequest')
    for request in SavioProjectAllocationRequest.objects.all():
        request.request_time = None
        request.approval_time = None
        request.completion_time = None
        request.save()


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_project_allocation_request_allocation_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsavioprojectallocationrequest',
            name='approval_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsavioprojectallocationrequest',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsavioprojectallocationrequest',
            name='request_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='savioprojectallocationrequest',
            name='approval_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savioprojectallocationrequest',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savioprojectallocationrequest',
            name='request_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.RunPython(
            add_times_to_existing_requests, reverse_code=nullify_times),
    ]
