# Generated by Django 3.2.5 on 2022-03-21 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_project_allocation_request_allocation_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsavioprojectallocationrequest',
            name='approval_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsavioprojectallocationrequest',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsavioprojectallocationrequest',
            name='request_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='savioprojectallocationrequest',
            name='approval_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savioprojectallocationrequest',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savioprojectallocationrequest',
            name='request_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
