# Generated by Django 3.2.5 on 2022-07-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_project_allocation_request_computing_allowance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsavioprojectallocationrequest',
            name='allocation_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='savioprojectallocationrequest',
            name='allocation_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
