# Generated by Django 3.2.5 on 2022-08-11 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('project', '0021_project_allocation_request_remove_allocation_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsavioprojectallocationrequest',
            name='billing_activity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.billingactivity'),
        ),
        migrations.AddField(
            model_name='savioprojectallocationrequest',
            name='billing_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_activity', to='billing.billingactivity'),
        ),
    ]
