# Generated by Django 4.2.11 on 2025-05-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocation', '0018_alter_allocation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovableAllocation',
            fields=[
            ],
            options={
                'permissions': (('can_move_allocations', 'Can move allocations'),),
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('allocation.allocation',),
        ),
    ]
