# Generated by Django 3.2.13 on 2022-05-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='orcid_id',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
