# Generated by Django 3.2.14 on 2022-10-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220721_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_class_projects_override',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_research_projects_override',
            field=models.IntegerField(default=-1),
        ),
    ]
