# Generated by Django 3.2.13 on 2022-05-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_orcid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='orcid_id',
            field=models.CharField(max_length=19, null=True),
        ),
    ]
