# Generated by Django 2.2.13 on 2021-03-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userdatausage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDataUsage',
        ),
    ]
