# Generated by Django 3.2.14 on 2024-09-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20221020_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='max_projects',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='division',
            field=models.CharField(default='', max_length=100),
        ),
    ]
