# Generated by Django 2.2.13 on 2020-12-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_add_user_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_agreement_signed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
