# Generated by Django 3.2.5 on 2022-06-06 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_add_billing_activity_to_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='host_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Change is_primary status in list display.'),
        ),
    ]
