# Generated by Django 3.2.5 on 2022-04-29 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_add_billing_activity_to_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Change is_primary status in list display.'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailaddress_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
