# Generated by Django 3.2.5 on 2022-08-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingactivity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='billingactivity',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='billingproject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalbillingactivity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalbillingactivity',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='historicalbillingproject',
            name='description',
        ),
    ]
