# Generated by Django 4.2.11 on 2024-09-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_of_science', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldofscience',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
