#!/bin/sh

# This script clears out the PostgreSQL database with the given name and
# loads in the data from the given dump file generated by pg_dump. It
# skips loading entries from the Job table.

if [ "$1" == "-h" ]; then
  echo "Usage: `basename $0` [name of database] [absolute path to dump file]"
  exit 0
fi

DB_NAME=$1
DUMP_FILE=$2

if ! [[ "$DUMP_FILE" = /* ]]
then
    echo "Path to database dump file must be absolute."
    exit 1
fi

if ! [[ -f $DUMP_FILE ]]
then
    echo "Database dump file must be a file."
    exit 1
fi

BIN=/usr/pgsql-9.6/bin/pg_restore

sudo -E su - postgres -c "$BIN -L <($BIN -l $DUMP_FILE | grep -v 'statistics_job') -d $DB_NAME $DUMP_FILE -c"
