# Generated by Django 2.2.18 on 2021-05-18 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0001_initial'),
        ('allocation', '0011_delete_allocationaccount'),
        ('ifx', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllocationProductUsage',
            new_name='AllocationUserProductUsage',
        ),
        migrations.RemoveField(
            model_name='allocationuserproductusage',
            name='allocation',
        ),
        migrations.AddField(
            model_name='allocationuserproductusage',
            name='allocation_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='allocation.HistoricalAllocationUser'),
            preserve_default=False,
        ),
    ]
