# Generated by Django 2.2.18 on 2021-07-07 19:06

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifxuser', '0009_auto_20210622_1416'),
        ('ifx', '0002_auto_20210518_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ifxuser.ifxuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
