# Generated by Django 2.2.18 on 2021-10-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifxuser', '0011_auto_20210727_1929'),
        ('project', '0002_remove_projectuser_usage'),
        ('ifx', '0003_suuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ifxuser.Organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.Project')),
            ],
        ),
    ]
