# Generated by Django 2.2.18 on 2021-10-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifxuser', '0011_auto_20210727_1929'),
        ('project', '0002_remove_projectuser_usage'),
        ('ifx', '0004_projectorganization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectorganization',
            unique_together={('organization', 'project')},
        ),
    ]
