# Generated by Django 4.2.11 on 2024-12-09 17:36

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifxuser', '0006_useraffiliation_detail'),
        ('ifx', '0005_auto_20211003_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdfrontIfxUser',
            fields=[
                ('ifxuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ifx_coldfrontifxuser',
            },
            bases=('ifxuser.ifxuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PreferredUsername',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifxid', models.CharField(max_length=255)),
                ('preferred_username', models.CharField(max_length=255)),
            ],
        ),
    ]
