# Generated by Django 4.2.11 on 2025-04-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0015_allocationstatuschoice_description'),
        ('ifxbilling', '0025_product_product_organization'),
        ('ifx', '0006_coldfrontifxuser_preferredusername'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.allocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ColdfrontIfxUser',
        ),
    ]
