# Generated by Django 4.2.14 on 2025-07-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifx', '0007_productallocation_delete_coldfrontifxuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreferredUsername',
        ),
    ]
