# SPDX-FileCopyrightText: (C) University at Buffalo
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.6 on 2026-08-04 00:25

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models

import coldfront.core.utils
import coldfront.models.deletion
import coldfront.utils.jsonschema


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("ras", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlurmQOS",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=coldfront.core.utils.CustomFieldJSONEncoder),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                ("description", models.CharField(blank=True, max_length=200, verbose_name="description")),
                (
                    "priority",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="QOS priority factor. Higher values increase a job's priority when this QOS is used. Maps to Priority in the dump format.",
                        null=True,
                        verbose_name="priority",
                    ),
                ),
                (
                    "max_submit_jobs_per_user",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of jobs a user can submit with this QOS. Maps to MaxSubmitJobsPU in the dump format.",
                        null=True,
                        verbose_name="max submit jobs per user",
                    ),
                ),
                (
                    "max_jobs_per_user",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of running jobs a user can have with this QOS. Maps to MaxJobsPU in the dump format.",
                        null=True,
                        verbose_name="max jobs per user",
                    ),
                ),
                (
                    "max_submit_jobs_per_account",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of jobs an account can submit with this QOS. Maps to MaxSubmitJobsPA in the dump format.",
                        null=True,
                        verbose_name="max submit jobs per account",
                    ),
                ),
                (
                    "max_jobs_per_account",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of running jobs an account can have with this QOS. Maps to MaxJobsPA in the dump format.",
                        null=True,
                        verbose_name="max jobs per account",
                    ),
                ),
                (
                    "max_wall_duration_per_job",
                    models.DurationField(
                        blank=True,
                        help_text="Maximum wall clock time per job using this QOS. Maps to MaxWallDurationPerJob in the dump format.",
                        null=True,
                        verbose_name="max wall duration per job",
                    ),
                ),
                (
                    "limit_factor",
                    models.FloatField(
                        blank=True,
                        help_text="A float that is factored into an association's GrpTRES limits. Maps to LimitFactor in the dump format.",
                        null=True,
                        verbose_name="limit factor",
                    ),
                ),
                (
                    "grace_time",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Preemption grace time in seconds. Jobs selected for preemption are given this much time before termination. Maps to GraceTime in the dump format.",
                        null=True,
                        verbose_name="grace time",
                    ),
                ),
            ],
            options={
                "verbose_name": "slurm qos",
                "verbose_name_plural": "slurm qos",
                "ordering": ["name"],
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SlurmUser",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=coldfront.core.utils.CustomFieldJSONEncoder),
                ),
                ("description", models.CharField(blank=True, max_length=200, verbose_name="description")),
                (
                    "default_wckey",
                    models.CharField(
                        blank=True,
                        help_text="Default wckey for fairshare and accounting.",
                        max_length=100,
                        null=True,
                        verbose_name="default wckey",
                    ),
                ),
                (
                    "admin_level",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(0, "Not Set"), (1, "None"), (2, "Operator"), (3, "Administrator")],
                        help_text="Slurm administrator level for this user. Not Set (0), None (1), Operator (2), or Administrator (3). Operators can modify accounting entities; Administrators have full control.",
                        null=True,
                        verbose_name="admin level",
                    ),
                ),
            ],
            options={
                "verbose_name": "slurm user",
                "verbose_name_plural": "slurm users",
                "ordering": ["cluster__name", "user__username"],
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SlurmAccount",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=coldfront.core.utils.CustomFieldJSONEncoder),
                ),
                ("description", models.CharField(blank=True, max_length=200, verbose_name="description")),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "fairshare",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="Account-level fairshare. When set, all user associations under this account inherit via Fairshare=parent in the dump. ",
                        null=True,
                        verbose_name="fairshare",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="core.TaggedItem",
                        to="core.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "slurm account",
                "verbose_name_plural": "slurm accounts",
                "ordering": ["cluster__name", "name"],
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SlurmAssociation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=coldfront.core.utils.CustomFieldJSONEncoder),
                ),
                ("description", models.CharField(blank=True, max_length=200, verbose_name="description")),
                (
                    "fairshare",
                    models.PositiveIntegerField(
                        blank=True,
                        default=1,
                        help_text="Fairshare value for this association. Determines relative priority within the fairshare tree.",
                        verbose_name="fairshare",
                    ),
                ),
                (
                    "max_jobs",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of jobs that can run simultaneously in this association.",
                        null=True,
                        verbose_name="max jobs",
                    ),
                ),
                (
                    "max_submit_jobs",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of jobs that can be submitted by this association.",
                        null=True,
                        verbose_name="max submit jobs",
                    ),
                ),
                (
                    "max_tres_per_job",
                    models.JSONField(
                        blank=True,
                        help_text='JSON dict of TRES limits per job (e.g., {"node":5,"cpu":20}).',
                        null=True,
                        verbose_name="max TRES per job",
                    ),
                ),
                (
                    "max_tres_mins_per_job",
                    models.JSONField(
                        blank=True,
                        help_text='JSON dict of TRES minute limits per job (e.g., {"cpu":360}).',
                        null=True,
                        verbose_name="max TRES minutes per job",
                    ),
                ),
                (
                    "max_wall_duration_per_job",
                    models.DurationField(
                        blank=True,
                        help_text="Maximum wall clock duration per job.",
                        null=True,
                        verbose_name="max wall duration per job",
                    ),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_extensions",
                        to="ras.allocation",
                        unique=True,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent account in the Slurm hierarchy for this association.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_associations",
                        to="slurm.slurmaccount",
                        verbose_name="parent account",
                    ),
                ),
                (
                    "slurm_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Slurm account for this allocation. Links the allocation to a named Slurm accounting account.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="associations",
                        to="slurm.slurmaccount",
                        verbose_name="Slurm account",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="core.TaggedItem",
                        to="core.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "slurm association",
                "verbose_name_plural": "slurm associations",
                "ordering": ["allocation__slug"],
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SlurmCluster",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=coldfront.core.utils.CustomFieldJSONEncoder),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "schema",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[coldfront.utils.jsonschema.validate_schema],
                        verbose_name="schema",
                    ),
                ),
                (
                    "locked",
                    models.BooleanField(
                        default=False,
                        help_text="Prevent users from submitting allocations for this resource.",
                        verbose_name="locked",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200, verbose_name="description")),
                (
                    "fairshare",
                    models.PositiveIntegerField(
                        blank=True,
                        default=1,
                        help_text="Default fairshare value for this cluster. Used as the root association's shares_raw. All associations under this cluster inherit unless overridden. Maps to Fairshare in the dump format.",
                        verbose_name="fairshare",
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Cluster features (GPU types, etc.) used to describe federated cluster capabilities. When submitting a federated job, --features filters which cluster receives the job.",
                        null=True,
                        verbose_name="features",
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        blank=True,
                        help_text="How this machine is classified.",
                        max_length=50,
                        null=True,
                        verbose_name="classification",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="core.TaggedItem",
                        to="core.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slurm_clusters",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "slurm cluster",
                "verbose_name_plural": "slurm clusters",
                "ordering": ["name"],
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name="slurmaccount",
            name="cluster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="slurm.slurmcluster",
                verbose_name="cluster",
            ),
        ),
        migrations.CreateModel(
            name="SlurmPartition",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=coldfront.core.utils.CustomFieldJSONEncoder),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "schema",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[coldfront.utils.jsonschema.validate_schema],
                        verbose_name="schema",
                    ),
                ),
                (
                    "locked",
                    models.BooleanField(
                        default=False,
                        help_text="Prevent users from submitting allocations for this resource.",
                        verbose_name="locked",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200, verbose_name="description")),
                (
                    "max_jobs",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of jobs that can run simultaneously in this partition.",
                        null=True,
                        verbose_name="max jobs",
                    ),
                ),
                (
                    "max_submit_jobs",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of jobs that can be submitted by this association.",
                        null=True,
                        verbose_name="max submit jobs",
                    ),
                ),
                (
                    "max_tres_per_job",
                    models.JSONField(
                        blank=True,
                        help_text='JSON dict of TRES limits per job (e.g., {"node":5,"cpu":20}).',
                        null=True,
                        verbose_name="max TRES per job",
                    ),
                ),
                (
                    "max_tres_per_node",
                    models.JSONField(
                        blank=True,
                        help_text='JSON dict of TRES limits per node (e.g., {"gpu":8}).',
                        null=True,
                        verbose_name="max TRES per node",
                    ),
                ),
                (
                    "max_tres_mins_per_job",
                    models.JSONField(
                        blank=True,
                        help_text='JSON dict of TRES minute limits per job (e.g., {"cpu":360}).',
                        null=True,
                        verbose_name="max TRES minutes per job",
                    ),
                ),
                (
                    "max_wall_duration_per_job",
                    models.DurationField(
                        blank=True,
                        help_text="Maximum wall clock duration per job.",
                        null=True,
                        verbose_name="max wall duration per job",
                    ),
                ),
                (
                    "fairshare",
                    models.PositiveIntegerField(
                        blank=True,
                        default=1,
                        help_text="Fairshare value for this partition's associations. Determines relative priority within the fairshare tree. Higher values allow more jobs before priority decays.",
                        verbose_name="fairshare",
                    ),
                ),
                (
                    "nodes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Comma-separated node list for this partition (e.g., node[01-64]).",
                        verbose_name="nodes",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Priority tier for scheduling and preemption. Higher priority partitions are scheduled first.",
                        null=True,
                        verbose_name="priority",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="If set, this is the default partition for jobs that do not specify one.",
                        verbose_name="default",
                    ),
                ),
                (
                    "default_time",
                    models.DurationField(
                        blank=True,
                        help_text="Default job time limit for this partition.",
                        null=True,
                        verbose_name="default time",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[("UP", "UP"), ("DOWN", "DOWN"), ("DRAIN", "DRAIN"), ("INACTIVE", "INACTIVE")],
                        help_text="Partition state (UP, DOWN, DRAIN, INACTIVE).",
                        max_length=20,
                        null=True,
                        verbose_name="state",
                    ),
                ),
                (
                    "preempt_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OFF", "OFF"),
                            ("SUSPEND", "SUSPEND"),
                            ("REQUEUE", "REQUEUE"),
                            ("CANCEL", "CANCEL"),
                            ("GANG", "GANG"),
                            ("WITHIN", "WITHIN"),
                            ("PRIORITY", "PRIORITY"),
                        ],
                        help_text="Preemption mode for this partition (e.g., OFF, SUSPEND, GANG, CANCEL).",
                        max_length=20,
                        null=True,
                        verbose_name="preempt mode",
                    ),
                ),
                (
                    "def_mem_per_cpu",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Default memory per CPU in MB for jobs in this partition.",
                        null=True,
                        verbose_name="default memory per CPU",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True, verbose_name="slug")),
                (
                    "allow_accounts",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Restrict which SlurmAccounts can submit jobs to this partition. When set, only associations under one of these accounts are permitted.",
                        related_name="allowed_partitions",
                        related_query_name="allowed_partition",
                        to="slurm.slurmaccount",
                        verbose_name="allowed accounts",
                    ),
                ),
            ],
            options={
                "verbose_name": "slurm partition",
                "verbose_name_plural": "slurm partitions",
                "ordering": ["cluster__name", "name"],
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
    ]
