# SPDX-FileCopyrightText: (C) University at Buffalo
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.6 on 2026-08-04 00:25

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("slurm", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="slurmpartition",
            name="allow_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Restrict partition access to specific ColdFront Groups. Users must be in one of these groups to submit allocations to this partition. Maps to AllowGroups in slurm.conf.",
                related_name="allowed_partitions",
                related_query_name="allowed_partition",
                to="users.group",
                verbose_name="allowed groups",
            ),
        ),
        migrations.AddField(
            model_name="slurmpartition",
            name="cluster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partitions",
                to="slurm.slurmcluster",
                verbose_name="cluster",
            ),
        ),
        migrations.AddField(
            model_name="slurmpartition",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="core.TaggedItem",
                to="core.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="slurmqos",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="core.TaggedItem",
                to="core.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="slurmpartition",
            name="allow_qos",
            field=models.ManyToManyField(
                blank=True,
                help_text="QOS whitelist for admission control. Only jobs requesting one of these QOSes are permitted to submit to this partition. Maps to AllowQOS in slurm.conf.",
                related_name="allowed_partitions",
                related_query_name="allowed_partition",
                to="slurm.slurmqos",
                verbose_name="allowed QOS",
            ),
        ),
        migrations.AddField(
            model_name="slurmpartition",
            name="qos",
            field=models.ForeignKey(
                blank=True,
                help_text="Partition-level QOS whose resource limits (max time, CPUs, memory) apply to every job in this partition. The partition QOS and the job's QOS are both enforced — the stricter limit wins. Maps to QOS in slurm.conf.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_partitions",
                to="slurm.slurmqos",
                verbose_name="QOS",
            ),
        ),
        migrations.AddField(
            model_name="slurmcluster",
            name="default_qos",
            field=models.ForeignKey(
                blank=True,
                help_text="Default QOS applied to jobs that do not specify one. Maps to DefaultQOS in the dump format",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="default_for_clusters",
                to="slurm.slurmqos",
                verbose_name="default QOS",
            ),
        ),
        migrations.AddField(
            model_name="slurmcluster",
            name="qos_list",
            field=models.ManyToManyField(
                blank=True,
                help_text="QOS options available on this cluster. Associations inherit these via QOS+= syntax.",
                related_name="clusters",
                related_query_name="cluster",
                to="slurm.slurmqos",
                verbose_name="QOS list",
            ),
        ),
        migrations.AddField(
            model_name="slurmassociation",
            name="default_qos",
            field=models.ForeignKey(
                blank=True,
                help_text="Default QOS for this association. Jobs under this association inherit this QOS unless they specify one.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="associations",
                to="slurm.slurmqos",
                verbose_name="default QOS",
            ),
        ),
        migrations.AddField(
            model_name="slurmassociation",
            name="qos_add",
            field=models.ManyToManyField(
                blank=True,
                help_text="QOSes to add to this association via QOS+= in the dump format. These are added on top of the cluster/account defaults.",
                related_name="added_to_associations",
                related_query_name="added_to_association",
                to="slurm.slurmqos",
                verbose_name="QOS add",
            ),
        ),
        migrations.AddField(
            model_name="slurmassociation",
            name="qos_remove",
            field=models.ManyToManyField(
                blank=True,
                help_text="QOSes to remove from this association via QOS-= in the dump format. These are subtracted from the inherited QOS list.",
                related_name="removed_from_associations",
                related_query_name="removed_from_association",
                to="slurm.slurmqos",
                verbose_name="QOS remove",
            ),
        ),
        migrations.AddField(
            model_name="slurmaccount",
            name="qos_add",
            field=models.ManyToManyField(
                blank=True,
                help_text="QOSes to add to this account via QOS+= in the dump format. These are added on top of the cluster defaults.",
                related_name="added_to_accounts",
                related_query_name="added_to_account",
                to="slurm.slurmqos",
                verbose_name="QOS add",
            ),
        ),
        migrations.AddField(
            model_name="slurmaccount",
            name="qos_remove",
            field=models.ManyToManyField(
                blank=True,
                help_text="QOSes to remove from this account via QOS-= in the dump format. These are subtracted from the inherited QOS list.",
                related_name="removed_from_accounts",
                related_query_name="removed_from_account",
                to="slurm.slurmqos",
                verbose_name="QOS remove",
            ),
        ),
        migrations.AddField(
            model_name="slurmuser",
            name="cluster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="slurm.slurmcluster",
                verbose_name="cluster",
            ),
        ),
        migrations.AddField(
            model_name="slurmuser",
            name="default_account",
            field=models.ForeignKey(
                help_text="User's default Slurm account on this cluster. Jobs submitted by this user without specifying an account use this.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="default_for_users",
                to="slurm.slurmaccount",
                verbose_name="default account",
            ),
        ),
        migrations.AddField(
            model_name="slurmuser",
            name="default_qos",
            field=models.ForeignKey(
                blank=True,
                help_text="Default QOS for this user on this cluster. Applies to all jobs regardless of association.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="default_for_users",
                to="slurm.slurmqos",
                verbose_name="default QOS",
            ),
        ),
        migrations.AddField(
            model_name="slurmuser",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="core.TaggedItem",
                to="core.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="slurmuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="slurm_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddConstraint(
            model_name="slurmpartition",
            constraint=models.UniqueConstraint(
                fields=("cluster", "name"), name="slurm_slurmpartition_unique_cluster_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="slurmaccount",
            constraint=models.UniqueConstraint(
                fields=("cluster", "name"), name="slurm_slurmaccount_unique_cluster_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="slurmuser",
            constraint=models.UniqueConstraint(fields=("user", "cluster"), name="slurm_slurmuser_unique_user_cluster"),
        ),
    ]
