# Generated by Django 5.1.7 on 2025-03-21 20:01

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocation', '0001_initial'),
        ('project', '0001_initial'),
        ('resource', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='resources',
            field=models.ManyToManyField(to='resource.resource'),
        ),
        migrations.AddField(
            model_name='allocationaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocationadminnote',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.allocation'),
        ),
        migrations.AddField(
            model_name='allocationadminnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AllocationAttributeUsage',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('allocation_attribute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='allocation.allocationattribute')),
                ('value', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='allocationattribute',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.allocation'),
        ),
        migrations.AddField(
            model_name='allocationattributechangerequest',
            name='allocation_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.allocationattribute'),
        ),
        migrations.AddField(
            model_name='allocationattribute',
            name='allocation_attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.allocationattributetype'),
        ),
        migrations.AddField(
            model_name='allocationchangerequest',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.allocation'),
        ),
        migrations.AddField(
            model_name='allocationattributechangerequest',
            name='allocation_change_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.allocationchangerequest'),
        ),
        migrations.AddField(
            model_name='allocationchangerequest',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.allocationchangestatuschoice', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.allocationstatuschoice', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='allocationuser',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.allocation'),
        ),
        migrations.AddField(
            model_name='allocationuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocationusernote',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.allocation'),
        ),
        migrations.AddField(
            model_name='allocationusernote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocationuser',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.allocationuserstatuschoice', verbose_name='Allocation User Status'),
        ),
        migrations.AddField(
            model_name='allocationattributetype',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.attributetype'),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.project'),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='allocation.allocationstatuschoice', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='historicalallocationattribute',
            name='allocation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='allocation.allocation'),
        ),
        migrations.AddField(
            model_name='historicalallocationattribute',
            name='allocation_attribute_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='allocation.allocationattributetype'),
        ),
        migrations.AddField(
            model_name='historicalallocationattribute',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalallocationattributechangerequest',
            name='allocation_attribute',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='allocation.allocationattribute'),
        ),
        migrations.AddField(
            model_name='historicalallocationattributechangerequest',
            name='allocation_change_request',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='allocation.allocationchangerequest'),
        ),
        migrations.AddField(
            model_name='historicalallocationattributechangerequest',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalallocationattributetype',
            name='attribute_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='allocation.attributetype'),
        ),
        migrations.AddField(
            model_name='historicalallocationattributetype',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalallocationattributeusage',
            name='allocation_attribute',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='allocation.allocationattribute'),
        ),
        migrations.AddField(
            model_name='historicalallocationattributeusage',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalallocationchangerequest',
            name='allocation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='allocation.allocation'),
        ),
        migrations.AddField(
            model_name='historicalallocationchangerequest',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalallocationchangerequest',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='allocation.allocationchangestatuschoice', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='historicalallocationuser',
            name='allocation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='allocation.allocation'),
        ),
        migrations.AddField(
            model_name='historicalallocationuser',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalallocationuser',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='allocation.allocationuserstatuschoice', verbose_name='Allocation User Status'),
        ),
        migrations.AddField(
            model_name='historicalallocationuser',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='allocationuser',
            unique_together={('user', 'allocation')},
        ),
    ]
