# SPDX-FileCopyrightText: (C) ColdFront Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 2.2.3 on 2019-07-18 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("resource", "0001_initial"),
        ("allocation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="resources",
            field=models.ManyToManyField(to="resource.Resource"),
        ),
        migrations.AddField(
            model_name="allocation",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="allocation.AllocationStatusChoice",
                verbose_name="Status",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="allocationuser",
            unique_together={("user", "allocation")},
        ),
    ]
