# Generated by Django 4.2.11 on 2025-01-31 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0001_initial"),
        ("allocation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalallocation",
            name="project",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="project.project",
            ),
        ),
        migrations.AddField(
            model_name="historicalallocation",
            name="status",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="allocation.allocationstatuschoice",
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="allocationusernote",
            name="allocation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="allocation.allocation"
            ),
        ),
        migrations.AddField(
            model_name="allocationusernote",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="allocationuser",
            name="allocation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="allocation.allocation"
            ),
        ),
        migrations.AddField(
            model_name="allocationuser",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="allocation.allocationuserstatuschoice",
                verbose_name="Allocation User Status",
            ),
        ),
        migrations.AddField(
            model_name="allocationuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="allocationchangerequest",
            name="allocation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="allocation.allocation"
            ),
        ),
        migrations.AddField(
            model_name="allocationchangerequest",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="allocation.allocationchangestatuschoice",
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="allocationattributetype",
            name="attribute_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="allocation.attributetype",
            ),
        ),
        migrations.AddField(
            model_name="allocationattributechangerequest",
            name="allocation_attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="allocation.allocationattribute",
            ),
        ),
        migrations.AddField(
            model_name="allocationattributechangerequest",
            name="allocation_change_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="allocation.allocationchangerequest",
            ),
        ),
        migrations.AddField(
            model_name="allocationattribute",
            name="allocation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="allocation.allocation"
            ),
        ),
        migrations.AddField(
            model_name="allocationattribute",
            name="allocation_attribute_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="allocation.allocationattributetype",
            ),
        ),
        migrations.AddField(
            model_name="allocationadminnote",
            name="allocation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="allocation.allocation"
            ),
        ),
        migrations.AddField(
            model_name="allocationadminnote",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="allocationaccount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="project.project"
            ),
        ),
    ]
