# SPDX-FileCopyrightText: (C) ColdFront Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 2.2.4 on 2019-10-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allocation", "0002_auto_20190718_1451"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalallocation",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
