# Generated by Django 2.2.13 on 2021-03-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0003_auto_20191018_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationuser',
            name='unit',
            field=models.TextField(default=None, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='allocationuser',
            name='usage',
            field=models.TextField(default=None, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocationuser',
            name='unit',
            field=models.TextField(default=None, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocationuser',
            name='usage',
            field=models.TextField(default=None, max_length=220, null=True),
        ),
    ]
