# Generated by Django 2.2.13 on 2021-03-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0003_auto_20191018_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationuser',
            name='unit',
            field=models.TextField(default='TB', max_length=20),
        ),
        migrations.AddField(
            model_name='allocationuser',
            name='usage',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='historicalallocationuser',
            name='unit',
            field=models.TextField(default='TB', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalallocationuser',
            name='usage',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=6),
        ),
    ]
