# Generated by Django 2.2.4 on 2019-10-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_auto_20190718_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationuser',
            name='usage',
            field=models.TextField(max_length = 220, null=True, default = None),
        ),
        migrations.AddField(
            model_name='allocationuser',
            name='unit',
            field=models.TextField(max_length = 220, null=True, default = None),
        ),
       
    ]
