# Generated by Django 2.2.18 on 2021-07-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0004_auto_20210715_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='leverage_multi_gpu_decision',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocation',
            name='leverage_multi_gpu_decision',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
