# SPDX-FileCopyrightText: (C) ColdFront Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 2.2.24 on 2021-11-17 19:13

from django.db import migrations


def create_status_choices(apps, schema_editor):
    AllocationChangeStatusChoice = apps.get_model("allocation", "AllocationChangeStatusChoice")
    for choice in (
        "Pending",
        "Approved",
        "Denied",
    ):
        AllocationChangeStatusChoice.objects.get_or_create(name=choice)


class Migration(migrations.Migration):
    dependencies = [
        ("allocation", "0004_auto_20211102_1017"),
    ]

    operations = [
        migrations.RunPython(create_status_choices),
    ]
