# Generated by Django 2.2.13 on 2021-01-08 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0004_add_user_attributes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocation',
            options={'ordering': ['end_date'], 'permissions': (('can_view_all_allocations', 'Can view all allocations'), ('can_review_allocation_requests', 'Can review allocation requests'), ('can_manage_invoice', 'Can manage invoice'), ('can_review_cluster_account_requests', 'Can review cluster account requests'))},
        ),
    ]
