# Generated by Django 2.2.13 on 2021-03-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0004_auto_20210309_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationuser',
            name='usage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='historicalallocationuser',
            name='usage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
