# Generated by Django 2.2.13 on 2021-03-06 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0004_auto_20210306'),
        ('allocation', '0003_auto_20191018_1049'),
    ]

    operations = [
    ]
