# Generated by Django 2.2.18 on 2021-07-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0005_auto_20210716_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='leverage_multi_gpu_decision',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocation',
            name='leverage_multi_gpu_decision',
            field=models.BooleanField(null=True),
        ),
    ]
