# Generated by Django 3.2.13 on 2022-07-01 14:40

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0005_auto_20211117_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocationaccount',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
        migrations.AlterModelOptions(
            name='allocationattributetype',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
        migrations.AlterModelOptions(
            name='allocationchangestatuschoice',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
        migrations.AlterModelOptions(
            name='allocationstatuschoice',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
        migrations.AlterModelOptions(
            name='allocationuserstatuschoice',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
        migrations.AlterModelOptions(
            name='attributetype',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
