# Generated by Django 2.2.18 on 2021-07-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0006_auto_20210726_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation',
            old_name='leverage_multi_gpu_decision',
            new_name='leverage_multiple_gpus',
        ),
        migrations.RenameField(
            model_name='historicalallocation',
            old_name='leverage_multi_gpu_decision',
            new_name='leverage_multiple_gpus',
        ),
    ]
