# Generated by Django 2.2.13 on 2021-03-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0006_auto_20210312_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationuser',
            name='allocation_group_usage_bytes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historicalallocationuser',
            name='allocation_group_usage_bytes',
            field=models.FloatField(default=0),
        ),
    ]
