# Generated by Django 3.2.14 on 2023-01-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0006_auto_20221020_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='confirm_best_practices',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='confirm_best_practices',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
