# Generated by Django 2.2.13 on 2021-03-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0006_auto_20210309_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationuser',
            name='usage_bytes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocationuser',
            name='usage_bytes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
