# Generated by Django 2.2.13 on 2021-03-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0007_auto_20210310_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationuser',
            name='unit',
            field=models.TextField(default='bytes', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalallocationuser',
            name='unit',
            field=models.TextField(default='bytes', max_length=20),
        ),
    ]
