# Generated by Django 3.2.14 on 2023-03-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0007_auto_20230109_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='actively_billing',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='billable_amount_annual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='billable_amount_monthly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='billing_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='billing_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='billing_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='fileset',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='gpu_workflow',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='mou_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='organization',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='quota_files',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='share_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='share_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='allocationattributetype',
            name='linked_allocation_attribute',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='actively_billing',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='billable_amount_annual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='billable_amount_monthly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='billing_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='billing_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='billing_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='fileset',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='gpu_workflow',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='mou_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='organization',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='quota_files',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='share_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='share_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocationattributetype',
            name='linked_allocation_attribute',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
