# Generated by Django 2.2.18 on 2021-07-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0008_auto_20210728_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='leverage_multiple_gpus',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocation',
            name='leverage_multiple_gpus',
            field=models.BooleanField(null=True),
        ),
    ]
