# Generated by Django 3.2.5 on 2022-07-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0009_allocationrenewalrequest_computing_allowance'),
        ('allocation', '0009_clusteraccessrequest_clusteraccessrequeststatuschoice'),
    ]

    operations = [
    ]
