# Generated by Django 2.2.18 on 2021-07-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0009_auto_20210728_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='leverage_multiple_gpus',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocation',
            name='leverage_multiple_gpus',
            field=models.IntegerField(null=True),
        ),
    ]
