# Generated by Django 2.2.13 on 2021-03-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0009_auto_20210324_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationuser',
            name='allocation_group_quota',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allocationuser',
            name='allocation_group_usage_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allocationuser',
            name='usage_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocationuser',
            name='allocation_group_quota',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocationuser',
            name='allocation_group_usage_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocationuser',
            name='usage_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
