# Generated by Django 2.2.18 on 2021-05-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0010_auto_20210325_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllocationAccount',
        ),
    ]
