# Generated by Django 2.2.18 on 2021-07-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0010_auto_20210729_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='leverage_multiple_gpus',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocation',
            name='leverage_multiple_gpus',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], null=True),
        ),
    ]
