# Generated by Django 3.2.5 on 2022-08-19 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0011_clusteraccessrequest_clusteraccessrequeststatuschoice_historicalclusteraccessrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusteraccessrequest',
            name='billing_activity',
        ),
        migrations.RemoveField(
            model_name='clusteraccessrequest',
            name='host_user',
        ),
        migrations.RemoveField(
            model_name='historicalclusteraccessrequest',
            name='billing_activity',
        ),
        migrations.RemoveField(
            model_name='historicalclusteraccessrequest',
            name='host_user',
        ),
    ]
