# Generated by Django 3.2.13 on 2022-08-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0005_auto_20211117_1413'),
        ('allocation', '0011_delete_allocationaccount'),
    ]

    operations = [
    ]
