# Generated by Django 2.2.18 on 2021-12-03 21:08

from django.db import migrations
from django.utils import timezone

from coldfront.core.allocation.models import AllocationAttributeType

try:
    AllocationAttributeType.objects.get(id=5)
except AllocationAttributeType.DoesNotExist:
    AllocationAttributeType.objects.create( id=5, created=timezone.now(),
        modified=timezone.now(), name="Quota_in_bytes", has_usage=True,
        is_required=False, is_unique=False, is_private=True, attribute_type_id=3)


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0011_delete_allocationaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationuser',
            name='allocation_group_quota',
        ),
        migrations.RemoveField(
            model_name='allocationuser',
            name='allocation_group_usage_bytes',
        ),
        migrations.RemoveField(
            model_name='historicalallocationuser',
            name='allocation_group_quota',
        ),
        migrations.RemoveField(
            model_name='historicalallocationuser',
            name='allocation_group_usage_bytes',
        ),


        migrations.RemoveField(
            model_name='allocationuser',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='allocationuser',
            name='usage',
        ),
        migrations.RemoveField(
            model_name='historicalallocationuser',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='historicalallocationuser',
            name='usage',
        ),
        migrations.RenameField(
            model_name='allocationuser',
            old_name='usage_bytes',
            new_name='usage',
        ),
        migrations.RenameField(
            model_name='historicalallocationuser',
            old_name='usage_bytes',
            new_name='usage',
        ),
    ]
