# Generated by Django 3.2.14 on 2024-01-16 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0007_auto_20240116_0907'),
        ('allocation', '0011_allocationremovalrequest_allocationremovalstatuschoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationUserRoleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=64)),
                ('is_user_default', models.BooleanField(default=False)),
                ('is_manager_default', models.BooleanField(default=False)),
                ('resources', models.ManyToManyField(blank=True, to='resource.Resource')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='allocationuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allocation.allocationuserrolechoice'),
        ),
        migrations.AddField(
            model_name='historicalallocationuser',
            name='role',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='allocation.allocationuserrolechoice'),
        ),
    ]
