# Generated by Django 2.2.18 on 2021-07-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0011_auto_20210729_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='leverage_multiple_gpus',
            field=models.IntegerField(choices=[('No', 'No'), ('Yes', 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocation',
            name='leverage_multiple_gpus',
            field=models.IntegerField(choices=[('No', 'No'), ('Yes', 'Yes')], null=True),
        ),
    ]
