# Generated by Django 3.2.13 on 2023-01-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0012_merge_20220802_1428'),
        ('allocation', '0013_allocationaccount'),
    ]

    operations = [
    ]

