# Generated by Django 3.2.17 on 2024-05-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0014_auto_20231211_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationstatuschoice',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
