# Generated by Django 2.2.18 on 2021-07-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0014_auto_20210729_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='training_or_inference',
            field=models.CharField(choices=[('training', 'Training'), ('inference', 'Inference'), ('both', 'Both')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='training_or_inference',
            field=models.CharField(choices=[('training', 'Training'), ('inference', 'Inference'), ('both', 'Both')], max_length=9, null=True),
        ),
    ]
