# Generated by Django 2.2.18 on 2021-07-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0015_auto_20210729_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='training_or_inference',
            field=models.CharField(choices=[('Training', 'Training'), ('Inference', 'Inference'), ('Both', 'Both')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocation',
            name='training_or_inference',
            field=models.CharField(choices=[('Training', 'Training'), ('Inference', 'Inference'), ('Both', 'Both')], max_length=9, null=True),
        ),
    ]
