# Generated by Django 4.2.11 on 2024-12-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0015_alter_historicalallocation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationattributechangerequest',
            name='old_value',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalallocationattributechangerequest',
            name='old_value',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allocationattribute',
            name='value',
            field=models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=128),
        ),
    ]
