# Generated by Django 2.2.18 on 2021-07-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0016_auto_20210729_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='dl_workflow',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='dl_workflow',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
    ]
