# Generated by Django 4.2.11 on 2025-01-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0016_allocationattributechangerequest_old_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationadminaction',
            name='action',
            field=models.CharField(max_length=256),
        ),
    ]
