# Generated by Django 2.2.18 on 2021-07-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0017_auto_20210729_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='applications_list',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='applications_list',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
