# Generated by Django 4.2.11 on 2025-02-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0017_alter_allocationadminaction_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocation',
            options={'ordering': ['end_date'], 'permissions': (('can_view_all_allocations', 'Can view all allocations'), ('can_review_allocation_requests', 'Can review allocation requests'), ('can_manage_invoice', 'Can manage invoice'))},
        ),
        migrations.DeleteModel(
            name='AllocationRemovalRequest',
        ),
        migrations.DeleteModel(
            name='AllocationRemovalStatusChoice',
        ),
    ]
