# Generated by Django 2.2.18 on 2021-08-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0018_auto_20210729_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='system',
            field=models.CharField(choices=[('Carbonate', 'Carbonate'), ('Big Red 3', 'BigRed3')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='system',
            field=models.CharField(choices=[('Carbonate', 'Carbonate'), ('Big Red 3', 'BigRed3')], max_length=9, null=True),
        ),
    ]
