# Generated by Django 2.2.18 on 2021-08-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0020_auto_20210817_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='applications_list',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='dl_workflow',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='for_coursework',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='leverage_multiple_gpus',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='system',
            field=models.CharField(blank=True, choices=[('Carbonate', 'Carbonate'), ('BigRed3', 'Big Red 3')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='training_or_inference',
            field=models.CharField(blank=True, choices=[('Training', 'Training'), ('Inference', 'Inference'), ('Both', 'Both')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocation',
            name='applications_list',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocation',
            name='dl_workflow',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocation',
            name='for_coursework',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocation',
            name='leverage_multiple_gpus',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocation',
            name='system',
            field=models.CharField(blank=True, choices=[('Carbonate', 'Carbonate'), ('BigRed3', 'Big Red 3')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocation',
            name='training_or_inference',
            field=models.CharField(blank=True, choices=[('Training', 'Training'), ('Inference', 'Inference'), ('Both', 'Both')], max_length=9, null=True),
        ),
    ]
