# Generated by Django 2.2.18 on 2021-08-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0021_auto_20210818_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='phi_association',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='phi_association',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
    ]
