# Generated by Django 2.2.18 on 2021-08-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0022_auto_20210818_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='access_level',
            field=models.CharField(blank=True, choices=[('', ''), ('Masked', 'Masked'), ('Unmasked', 'Unmasked')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='access_level',
            field=models.CharField(blank=True, choices=[('', ''), ('Masked', 'Masked'), ('Unmasked', 'Unmasked')], max_length=8, null=True),
        ),
    ]
