# Generated by Django 2.2.18 on 2021-08-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0023_auto_20210818_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='confirm_understanding',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='confirm_understanding',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
