# Generated by Django 2.2.18 on 2021-08-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0024_auto_20210818_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='confirm_understanding',
            field=models.CharField(blank=True, choices=[('', ''), ('Yes', 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocation',
            name='confirm_understanding',
            field=models.CharField(blank=True, choices=[('', ''), ('Yes', 'Yes')], max_length=4, null=True),
        ),
    ]
