# Generated by Django 2.2.18 on 2021-08-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0025_auto_20210818_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='access_level',
            field=models.CharField(blank=True, choices=[('Masked', 'Masked'), ('Unmasked', 'Unmasked')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='confirm_understanding',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocation',
            name='access_level',
            field=models.CharField(blank=True, choices=[('Masked', 'Masked'), ('Unmasked', 'Unmasked')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocation',
            name='confirm_understanding',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
