# Generated by Django 2.2.18 on 2021-08-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0026_auto_20210820_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocation',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
