# Generated by Django 2.2.18 on 2021-08-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0027_auto_20210824_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='storage_space',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='storage_space',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
