# Generated by Django 2.2.18 on 2021-08-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0030_auto_20210827_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='fiscal_officer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='fiscal_officer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
