# Generated by Django 2.2.18 on 2021-08-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0031_auto_20210827_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='account_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='sub_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='account_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='sub_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
