# Generated by Django 2.2.18 on 2021-08-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0032_auto_20210827_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='data_management_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='devices_ip_addresses',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='it_pros',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='data_management_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='devices_ip_addresses',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='it_pros',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
