# Generated by Django 2.2.18 on 2021-09-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0034_auto_20210902_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='project_directory_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='prorated_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='project_directory_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='prorated_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
