# Generated by Django 2.2.18 on 2021-09-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0035_auto_20210908_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='project_directory_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocation',
            name='project_directory_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
