# Generated by Django 2.2.18 on 2021-09-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0036_auto_20210908_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation',
            old_name='prorated_amount',
            new_name='total_cost',
        ),
        migrations.RenameField(
            model_name='historicalallocation',
            old_name='prorated_amount',
            new_name='total_cost',
        ),
    ]
