# Generated by Django 2.2.18 on 2021-09-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0037_auto_20210909_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='campus_affiliation',
            field=models.CharField(blank=True, choices=[('BL', 'IU Bloomington'), ('IN', 'IUPUI (Indianapolis)'), ('CO', 'IUPUC (Columbus)'), ('EA', 'IU East (Richmond)'), ('FW', 'IU Fort Wayne'), ('CO', 'IU Kokomo'), ('NW', 'IU Northwest (Gary)'), ('SB', 'IU South Bend'), ('SE', 'IU Southeast (New Albany)'), ('OR', 'Other')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='faculty_email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='first_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='store_ephi',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='campus_affiliation',
            field=models.CharField(blank=True, choices=[('BL', 'IU Bloomington'), ('IN', 'IUPUI (Indianapolis)'), ('CO', 'IUPUC (Columbus)'), ('EA', 'IU East (Richmond)'), ('FW', 'IU Fort Wayne'), ('CO', 'IU Kokomo'), ('NW', 'IU Northwest (Gary)'), ('SB', 'IU South Bend'), ('SE', 'IU Southeast (New Albany)'), ('OR', 'Other')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='faculty_email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='first_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='store_ephi',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
