# Generated by Django 2.2.18 on 2021-09-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0038_auto_20210909_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='storage_space_with_unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='storage_space_with_unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='storage_space',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalallocation',
            name='storage_space',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
