# Generated by Django 4.2.11 on 2024-12-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_historicaldepartment_historicaldepartmentmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldepartmentmember',
            name='detail',
            field=models.CharField(blank=True, help_text='Additional details about the affiliation (e.g. Graduate Student)', max_length=255, null=True),
        ),
    ]
