# SPDX-FileCopyrightText: (C) ColdFront Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 2.2.4 on 2020-01-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publication", "0002_auto_20191223_1115"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicationsource",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="publicationsource",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
