# Generated by Django 3.2.13 on 2022-05-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_add_manual_publication_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpublication',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Archived', 'Archived'), ('Pending', 'Pending')], default='Active', max_length=16),
        ),
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Archived', 'Archived'), ('Pending', 'Pending')], default='Active', max_length=16),
        ),
    ]
