# Generated by Django 2.0.6 on 2018-07-31 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['active_until'], 'permissions': (('can_view_all_subscriptions', 'Can see all subscriptions'), ('can_review_pending_subscriptions', 'Can review pending subscriptions'))},
        ),
    ]
