# Generated by Django 2.0.6 on 2018-08-03 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20180731_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subscriptionattributetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subscriptionstatuschoice',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subscriptionuserstatuschoice',
            options={'ordering': ['name']},
        ),
    ]
