# Generated by Django 2.1 on 2018-09-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_auto_20180831_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionadmincomment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='subscriptionusercomment',
            old_name='user',
            new_name='author',
        ),
    ]
