# Generated by Django 3.2.5 on 2021-07-17 22:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_project_allocation_request_rename_mou'),
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUserTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('allocation', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=11, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('100000000.00')), django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('project_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='project.projectuser')),
            ],
            options={
                'verbose_name': 'Project User Transaction',
            },
        ),
        migrations.CreateModel(
            name='ProjectTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('allocation', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=11, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('100000000.00')), django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='project.project')),
            ],
            options={
                'verbose_name': 'Project Transaction',
            },
        ),
    ]
