# Generated by Django 4.2.11 on 2024-11-26 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='mailing_lists',
            field=models.ManyToManyField(blank=True, to='announcements.announcementmailinglistchoice'),
        ),
        migrations.AlterField(
            model_name='announcementcategorychoice',
            name='default_mailing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='announcements.announcementmailinglistchoice'),
        ),
        migrations.AlterField(
            model_name='announcementcategorychoice',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='announcements.announcementcategorychoice'),
        ),
    ]
