# Generated by Django 4.2.11 on 2024-12-12 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0002_alter_announcement_mailing_lists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementcategorychoice',
            name='default_mailing_list',
        ),
        migrations.RemoveField(
            model_name='announcementcategorychoice',
            name='parent_category',
        ),
        migrations.AlterField(
            model_name='announcementmailinglistchoice',
            name='subcribed',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
