# Generated by Django 4.2.11 on 2024-12-17 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0003_remove_announcementcategorychoice_default_mailing_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='announcements.announcementcategorychoice'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='mailing_lists',
            field=models.ManyToManyField(blank=True, null=True, to='announcements.announcementmailinglistchoice'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
