# Generated by Django 4.2.11 on 2025-01-27 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0005_alter_announcement_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='book_marked',
            field=models.ManyToManyField(blank=True, related_name='book_marked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='details_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalannouncement',
            name='details_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
