# Generated by Django 2.1 on 2018-08-24 21:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(255)])),
                ('grant_number', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(255)], verbose_name='Grant Number from funding agency')),
                ('role', models.CharField(choices=[('PI', 'Principal Investigator (PI)'), ('CoPI', 'Co-Principal Investigator (CoPI)'), ('SP', 'Senior Personnel (SP)')], max_length=10)),
                ('grant_pi_full_name', models.CharField(blank=True, max_length=255)),
                ('other_funding_agency', models.CharField(blank=True, max_length=255)),
                ('other_award_number', models.CharField(blank=True, max_length=255)),
                ('grant_start', models.DateField(verbose_name='Grant Start Date')),
                ('grant_end', models.DateField(verbose_name='Grant End Date')),
                ('percent_credit', models.FloatField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('direct_funding', models.FloatField()),
                ('total_amount_awarded', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Grants',
            },
        ),
        migrations.CreateModel(
            name='GrantFundingAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrantStatusChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='grant',
            name='funding_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grant.GrantFundingAgency'),
        ),
        migrations.AddField(
            model_name='grant',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AddField(
            model_name='grant',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grant.GrantStatusChoice'),
        ),
    ]
