# Generated by Django 2.0.6 on 2018-08-17 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('grant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AddField(
            model_name='grant',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grant.GrantStatusChoice'),
        ),
    ]
