# Generated by Django 2.0.6 on 2018-07-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='rf_award_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
