# Generated by Django 2.0.6 on 2018-08-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant', '0002_auto_20180730_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='pi_full_name',
        ),
        migrations.AddField(
            model_name='grant',
            name='grant_pi_full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Grant PI Full Name'),
        ),
    ]
