# Generated by Django 2.0.6 on 2018-08-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant', '0004_auto_20180801_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='role',
            field=models.CharField(choices=[('PI', 'Principal Investigator (PI)'), ('CoPI', 'Co-Principal Investigator (CoPI)'), ('SP', 'Senior Personnel (SP)')], max_length=10),
        ),
    ]
