# SPDX-FileCopyrightText: (C) University at Buffalo
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.6 on 2026-08-04 00:25

import re

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models

import coldfront.core.models.customfields
import coldfront.core.utils
import coldfront.models.deletion
import coldfront.models.fields
import coldfront.utils.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomField",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("longtext", "Text (long)"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("boolean", "Boolean (true/false)"),
                            ("date", "Date"),
                            ("datetime", "Date & time"),
                            ("select", "Selection"),
                            ("multiselect", "Multiple selection"),
                            ("object", "Object"),
                            ("multiobject", "Multiple objects"),
                        ],
                        default="text",
                        help_text="The type of data this custom field holds",
                        max_length=50,
                        verbose_name="type",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal field name",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                flags=re.RegexFlag["IGNORECASE"],
                                message="Only alphanumeric characters and underscores are allowed.",
                                regex="^[a-z0-9_]+$",
                            ),
                            django.core.validators.RegexValidator(
                                flags=re.RegexFlag["IGNORECASE"],
                                inverse_match=True,
                                message="Double underscores are not permitted in custom field names.",
                                regex="__",
                            ),
                        ],
                        verbose_name="name",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Name of the field as displayed to users (if not provided, 'the field's name will be used)",
                        max_length=50,
                        verbose_name="label",
                    ),
                ),
                (
                    "group_name",
                    models.CharField(
                        blank=True,
                        help_text="Custom fields within the same group will be displayed together",
                        max_length=50,
                        verbose_name="group name",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200, verbose_name="description")),
                (
                    "required",
                    models.BooleanField(
                        default=False,
                        help_text="This field is required when creating new objects or editing an existing object.",
                        verbose_name="required",
                    ),
                ),
                (
                    "unique",
                    models.BooleanField(
                        default=False,
                        help_text="The value of this field must be unique for the assigned object",
                        verbose_name="must be unique",
                    ),
                ),
                (
                    "search_weight",
                    models.PositiveSmallIntegerField(
                        default=1000,
                        help_text="Weighting for search. Lower values are considered more important. Fields with a search weight of zero will be ignored.",
                        verbose_name="search weight",
                    ),
                ),
                (
                    "filter_logic",
                    models.CharField(
                        choices=[("disabled", "Disabled"), ("loose", "Loose"), ("exact", "Exact")],
                        default="loose",
                        help_text="Loose matches any instance of a given string; exact matches the entire field.",
                        max_length=50,
                        verbose_name="filter logic",
                    ),
                ),
                (
                    "default",
                    models.JSONField(
                        blank=True,
                        help_text='Default value for the field (must be a JSON value). Encapsulate strings with double quotes (e.g. "Foo").',
                        null=True,
                        verbose_name="default",
                    ),
                ),
                (
                    "related_object_filter",
                    models.JSONField(
                        blank=True,
                        help_text='Filter the object selection choices using a query_params dict (must be a JSON value).Encapsulate strings with double quotes (e.g. "Foo").',
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Fields with higher weights appear lower in a form.",
                        verbose_name="display weight",
                    ),
                ),
                (
                    "validation_minimum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Minimum allowed value (for numeric fields)",
                        max_digits=16,
                        null=True,
                        verbose_name="minimum value",
                    ),
                ),
                (
                    "validation_maximum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Maximum allowed value (for numeric fields)",
                        max_digits=16,
                        null=True,
                        verbose_name="maximum value",
                    ),
                ),
                (
                    "validation_regex",
                    models.CharField(
                        blank=True,
                        help_text="Regular expression to enforce on text field values. Use ^ and $ to force matching of entire string. For example, <code>^[A-Z]{3}$</code> will limit values to exactly three uppercase letters.",
                        max_length=500,
                        validators=[coldfront.utils.validators.validate_regex],
                        verbose_name="validation regex",
                    ),
                ),
                (
                    "ui_visible",
                    models.CharField(
                        choices=[("always", "Always"), ("if-set", "If set"), ("hidden", "Hidden")],
                        default="always",
                        help_text="Specifies whether the custom field is displayed in the UI",
                        max_length=50,
                        verbose_name="UI visible",
                    ),
                ),
                (
                    "ui_editable",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No"), ("hidden", "Hidden")],
                        default="yes",
                        help_text="Specifies whether the custom field value can be edited in the UI",
                        max_length=50,
                        verbose_name="UI editable",
                    ),
                ),
                (
                    "required_action",
                    models.CharField(
                        blank=True,
                        help_text="Specifies the required action that must be granted to the user in order to edit the custom field",
                        max_length=50,
                        null=True,
                        verbose_name="Required Action",
                    ),
                ),
                (
                    "is_cloneable",
                    models.BooleanField(
                        default=False,
                        help_text="Replicate this value when cloning objects",
                        verbose_name="is cloneable",
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="comments")),
            ],
            options={
                "verbose_name": "custom field",
                "verbose_name_plural": "custom fields",
                "ordering": ["group_name", "weight", "name"],
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
            managers=[
                ("objects", coldfront.core.models.customfields.CustomFieldManager()),
            ],
        ),
        migrations.CreateModel(
            name="CustomFieldChoiceSet",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("choices", django_jsonform.models.fields.JSONField()),
                (
                    "order_alphabetically",
                    models.BooleanField(default=False, help_text="Choices are automatically ordered alphabetically"),
                ),
            ],
            options={
                "verbose_name": "custom field choice set",
                "verbose_name_plural": "custom field choice sets",
                "ordering": ("name",),
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CustomLink",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
                (
                    "link_text",
                    models.TextField(help_text="Jinja2 template code for link text", verbose_name="link text"),
                ),
                ("link_url", models.TextField(help_text="Jinja2 template code for link URL", verbose_name="link URL")),
                ("weight", models.PositiveSmallIntegerField(default=100, verbose_name="weight")),
                (
                    "group_name",
                    models.CharField(
                        blank=True,
                        help_text="Links with the same group will appear as a dropdown menu",
                        max_length=50,
                        verbose_name="group name",
                    ),
                ),
                (
                    "button_class",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("blue", "Blue"),
                            ("indigo", "Indigo"),
                            ("purple", "Purple"),
                            ("pink", "Pink"),
                            ("red", "Red"),
                            ("orange", "Orange"),
                            ("yellow", "Yellow"),
                            ("green", "Green"),
                            ("teal", "Teal"),
                            ("cyan", "Cyan"),
                            ("gray", "Gray"),
                            ("black", "Black"),
                            ("white", "White"),
                            ("ghost-dark", "Link"),
                        ],
                        default="default",
                        help_text="The class of the first link in a group will be used for the dropdown button",
                        max_length=30,
                        verbose_name="button class",
                    ),
                ),
                (
                    "new_window",
                    models.BooleanField(
                        default=False, help_text="Force link to open in a new window", verbose_name="new window"
                    ),
                ),
            ],
            options={
                "verbose_name": "custom link",
                "verbose_name_plural": "custom links",
                "ordering": ["group_name", "weight", "name"],
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("scheduled", models.DateTimeField(blank=True, null=True, verbose_name="scheduled")),
                (
                    "interval",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Recurrence interval (in minutes)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="interval",
                    ),
                ),
                ("started", models.DateTimeField(blank=True, null=True, verbose_name="started")),
                ("completed", models.DateTimeField(blank=True, null=True, verbose_name="completed")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("errored", "Errored"),
                        ],
                        default="pending",
                        max_length=30,
                        verbose_name="status",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="data",
                    ),
                ),
                ("error", models.TextField(blank=True, editable=False, verbose_name="error")),
                ("job_id", models.UUIDField(unique=True, verbose_name="job ID")),
                (
                    "queue_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the queue in which this job was enqueued",
                        max_length=100,
                        verbose_name="queue name",
                    ),
                ),
                (
                    "notifications",
                    models.CharField(
                        choices=[("always", "Always"), ("on_failure", "On failure"), ("never", "Never")],
                        default="always",
                        max_length=30,
                        verbose_name="notifications",
                    ),
                ),
                (
                    "log_entries",
                    models.JSONField(
                        blank=True,
                        decoder=coldfront.core.utils.JobLogDecoder,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        verbose_name="log entries",
                    ),
                ),
                (
                    "task_path",
                    models.TextField(
                        blank=True,
                        help_text="Dotted module path of the Task function to execute",
                        verbose_name="task path",
                    ),
                ),
                (
                    "args_kwargs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Serialized positional and keyword arguments for the task",
                        verbose_name="task arguments",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Queue priority (higher = sooner)", verbose_name="priority"
                    ),
                ),
                (
                    "worker_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Worker identifiers that have processed this job",
                        verbose_name="worker IDs",
                    ),
                ),
            ],
            options={
                "verbose_name": "job",
                "verbose_name_plural": "jobs",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ObjectChange",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="time")),
                ("user_name", models.CharField(editable=False, max_length=150, verbose_name="user name")),
                ("request_id", models.UUIDField(db_index=True, editable=False, verbose_name="request ID")),
                (
                    "action",
                    models.CharField(
                        choices=[("create", "Created"), ("update", "Updated"), ("delete", "Deleted")],
                        max_length=50,
                        verbose_name="action",
                    ),
                ),
                ("changed_object_id", models.PositiveBigIntegerField()),
                ("related_object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("object_repr", models.CharField(editable=False, max_length=200)),
                ("message", models.CharField(blank=True, editable=False, max_length=200, verbose_name="message")),
                (
                    "prechange_data",
                    models.JSONField(blank=True, editable=False, null=True, verbose_name="pre-change data"),
                ),
                (
                    "postchange_data",
                    models.JSONField(blank=True, editable=False, null=True, verbose_name="post-change data"),
                ),
            ],
            options={
                "verbose_name": "object change",
                "verbose_name_plural": "object changes",
                "ordering": ["-time"],
            },
        ),
        migrations.CreateModel(
            name="ObjectType",
            fields=[
                (
                    "contenttype_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="object_type",
                        serialize=False,
                        to="contenttypes.contenttype",
                    ),
                ),
                ("public", models.BooleanField(default=False)),
                ("features", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "object type",
                "verbose_name_plural": "object types",
                "ordering": ("app_label", "model"),
            },
            bases=("contenttypes.contenttype",),
        ),
        migrations.CreateModel(
            name="SavedFilter",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="slug")),
                ("description", models.CharField(blank=True, max_length=200, verbose_name="description")),
                ("weight", models.PositiveSmallIntegerField(default=100, verbose_name="weight")),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
                ("shared", models.BooleanField(default=True, verbose_name="shared")),
                ("parameters", models.JSONField(verbose_name="parameters")),
            ],
            options={
                "verbose_name": "saved filter",
                "verbose_name_plural": "saved filters",
                "ordering": ("weight", "name"),
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TableConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                ("table", models.CharField(max_length=100, verbose_name="table")),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("description", models.CharField(blank=True, max_length=200, verbose_name="description")),
                ("weight", models.PositiveSmallIntegerField(default=1000, verbose_name="weight")),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
                ("shared", models.BooleanField(default=True, verbose_name="shared")),
                ("columns", models.JSONField(blank=True, default=list, null=True, verbose_name="columns")),
                ("ordering", models.JSONField(blank=True, default=list, null=True, verbose_name="ordering")),
            ],
            options={
                "verbose_name": "table config",
                "verbose_name_plural": "table configs",
                "ordering": ("weight", "name"),
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                ("slug", models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name="slug")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("color", coldfront.models.fields.ColorField(default="9e9e9e", max_length=6, verbose_name="color")),
                ("description", models.CharField(blank=True, max_length=200, verbose_name="description")),
                ("weight", models.PositiveSmallIntegerField(default=1000, verbose_name="weight")),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "ordering": ("weight", "name"),
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TaggedItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.IntegerField(db_index=True, verbose_name="object ID")),
            ],
            options={
                "verbose_name": "tagged item",
                "verbose_name_plural": "tagged items",
            },
        ),
        migrations.CreateModel(
            name="CommentEntry",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=coldfront.core.utils.CustomFieldJSONEncoder),
                ),
                ("assigned_object_id", models.PositiveBigIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("danger", "Danger"),
                        ],
                        default="info",
                        max_length=30,
                        verbose_name="kind",
                    ),
                ),
                ("comments", models.TextField(verbose_name="comments")),
                (
                    "assigned_object_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "verbose_name": "comment entry",
                "verbose_name_plural": "comment entries",
                "ordering": ("-created",),
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
    ]
