# SPDX-FileCopyrightText: (C) University at Buffalo
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.6 on 2026-08-04 00:25

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="commententry",
            name="created_by",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="customfield",
            name="object_types",
            field=models.ManyToManyField(
                help_text="The object(s) to which this field applies.",
                related_name="custom_fields",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="customfield",
            name="related_object_type",
            field=models.ForeignKey(
                blank=True,
                help_text="The type of ColdFront object this field maps to (for object fields)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="customfield",
            name="choice_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="choices_for",
                to="core.customfieldchoiceset",
                verbose_name="choice set",
            ),
        ),
        migrations.AddField(
            model_name="customlink",
            name="object_types",
            field=models.ManyToManyField(
                help_text="The object type(s) to which this link applies.",
                related_name="custom_links",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="object_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="objectchange",
            name="changed_object_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="contenttypes.contenttype"
            ),
        ),
        migrations.AddField(
            model_name="objectchange",
            name="related_object_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="objectchange",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="savedfilter",
            name="object_types",
            field=models.ManyToManyField(
                help_text="The object type(s) to which this filter applies.",
                related_name="saved_filters",
                to="core.objecttype",
            ),
        ),
        migrations.AddField(
            model_name="savedfilter",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tableconfig",
            name="object_type",
            field=models.ForeignKey(
                help_text="The table's object type",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="table_configs",
                to="core.objecttype",
            ),
        ),
        migrations.AddField(
            model_name="tableconfig",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="object_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="The object type(s) to which this tag can be applied.",
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="taggeditem",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_tagged_items",
                to="contenttypes.contenttype",
                verbose_name="content type",
            ),
        ),
        migrations.AddField(
            model_name="taggeditem",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_items", to="core.tag"
            ),
        ),
        migrations.AddField(
            model_name="commententry",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="core.TaggedItem",
                to="core.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddIndex(
            model_name="customlink",
            index=models.Index(fields=["group_name", "weight", "name"], name="core_custom_group_n_a053a2_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["-created"], name="core_job_created_efa7cb_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["object_type", "object_id"], name="core_job_object__c664ac_idx"),
        ),
        migrations.AddIndex(
            model_name="objectchange",
            index=models.Index(
                fields=["changed_object_type", "changed_object_id"], name="core_object_changed_c227ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="objectchange",
            index=models.Index(
                fields=["related_object_type", "related_object_id"], name="core_object_related_3375d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedfilter",
            index=models.Index(fields=["weight", "name"], name="core_savedfilter_weight_name"),
        ),
        migrations.AddIndex(
            model_name="tableconfig",
            index=models.Index(fields=["weight", "name"], name="core_tablec_weight_96d0e8_idx"),
        ),
        migrations.AddIndex(
            model_name="taggeditem",
            index=models.Index(fields=["content_type", "object_id"], name="core_tagged_content_0b937e_idx"),
        ),
        migrations.AddIndex(
            model_name="commententry",
            index=models.Index(fields=["-created"], name="core_commen_created_973719_idx"),
        ),
        migrations.AddIndex(
            model_name="commententry",
            index=models.Index(
                fields=["assigned_object_type", "assigned_object_id"], name="core_commen_assigne_4f7609_idx"
            ),
        ),
    ]
