# SPDX-FileCopyrightText: (C) University at Buffalo
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.6 on 2026-08-04 00:25

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models

import coldfront.core.utils
import coldfront.models.deletion
import coldfront.utils.jsonschema


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("ras", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageResource",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=coldfront.core.utils.CustomFieldJSONEncoder),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "schema",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[coldfront.utils.jsonschema.validate_schema],
                        verbose_name="schema",
                    ),
                ),
                (
                    "locked",
                    models.BooleanField(
                        default=False,
                        help_text="Prevent users from submitting allocations for this resource.",
                        verbose_name="locked",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200, verbose_name="description")),
                (
                    "path_template",
                    models.CharField(
                        default="/mnt/{{project.slug}}/{{allocation.slug}}",
                        help_text="Template for auto-generating storage paths. Supports {project.<attr>}, {resource.<attr>}, and {allocation.id}.",
                        max_length=500,
                        verbose_name="path template",
                    ),
                ),
                (
                    "capacity_bytes",
                    models.PositiveBigIntegerField(
                        blank=True,
                        default=None,
                        help_text="Maximum total allocation across all quotas on this resource. Leave empty for unlimited.",
                        null=True,
                        verbose_name="capacity",
                    ),
                ),
                (
                    "allocated_bytes",
                    models.PositiveBigIntegerField(
                        default=0,
                        editable=False,
                        help_text="Sum of hard_limit_bytes for all active quotas. Updated automatically.",
                        verbose_name="allocated",
                    ),
                ),
                (
                    "used_bytes",
                    models.PositiveBigIntegerField(
                        default=0,
                        editable=False,
                        help_text="Sum of actual usage from all active quotas. Updated by sync.",
                        verbose_name="used",
                    ),
                ),
            ],
            options={
                "verbose_name": "storage resource",
                "verbose_name_plural": "storage resources",
                "ordering": ["name"],
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StorageSnapshotPolicy",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=coldfront.core.utils.CustomFieldJSONEncoder),
                ),
                ("description", models.CharField(blank=True, max_length=200, verbose_name="description")),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=50,
                        verbose_name="interval",
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        help_text="Number of days to retain snapshots.", verbose_name="retention days"
                    ),
                ),
                ("extra_config", models.JSONField(blank=True, default=dict, verbose_name="extra configuration")),
            ],
            options={
                "verbose_name": "storage snapshot policy",
                "verbose_name_plural": "storage snapshot policies",
                "ordering": ["cluster__name", "name"],
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StorageCluster",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=coldfront.core.utils.CustomFieldJSONEncoder),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "backend_path",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Dotted Python path to a StorageBackend subclass, e.g. 'coldfront.storage.backends.vast.VastBackend'. Leave empty for clusters with no backend (sync jobs will skip them).",
                        max_length=500,
                        null=True,
                        verbose_name="backend path",
                    ),
                ),
                ("auto_sync_enabled", models.BooleanField(default=False, verbose_name="auto sync enabled")),
                (
                    "sync_interval",
                    models.IntegerField(
                        default=1440, help_text="Minutes between automatic syncs.", verbose_name="sync interval"
                    ),
                ),
                (
                    "capacity_bytes",
                    models.PositiveBigIntegerField(
                        blank=True,
                        default=None,
                        help_text="Total storage capacity of this cluster in bytes. Leave empty for unlimited.",
                        null=True,
                        verbose_name="capacity",
                    ),
                ),
                (
                    "allocated_bytes",
                    models.PositiveBigIntegerField(
                        default=0,
                        editable=False,
                        help_text="Sum of hard_limit_bytes for all active quotas on this cluster. Updated automatically.",
                        verbose_name="allocated",
                    ),
                ),
                (
                    "used_bytes",
                    models.PositiveBigIntegerField(
                        default=0,
                        editable=False,
                        help_text="Sum of actual usage from all active quotas on this cluster. Updated by sync.",
                        verbose_name="used",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="core.TaggedItem",
                        to="core.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "storage cluster",
                "verbose_name_plural": "storage clusters",
                "ordering": ["name"],
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StorageQuota",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=coldfront.core.utils.CustomFieldJSONEncoder),
                ),
                ("description", models.CharField(blank=True, max_length=200, verbose_name="description")),
                ("path", models.CharField(max_length=500, verbose_name="path")),
                ("path_mode", models.PositiveSmallIntegerField(default=2770, verbose_name="path mode")),
                (
                    "hard_limit_bytes",
                    models.PositiveBigIntegerField(
                        blank=True, help_text="Quota limit in bytes.", null=True, verbose_name="hard limit"
                    ),
                ),
                (
                    "soft_limit_bytes",
                    models.PositiveBigIntegerField(
                        blank=True, help_text="Soft quota limit in bytes.", null=True, verbose_name="soft limit"
                    ),
                ),
                (
                    "hard_limit_files",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Hard limit on number of files.",
                        null=True,
                        verbose_name="hard limit files",
                    ),
                ),
                (
                    "soft_limit_files",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Soft limit on number of files.",
                        null=True,
                        verbose_name="soft limit files",
                    ),
                ),
                ("grace_period", models.DurationField(blank=True, null=True, verbose_name="grace period")),
                (
                    "share_type",
                    models.CharField(
                        choices=[("posix", "POSIX"), ("smb", "SMB"), ("nfs", "NFS")],
                        default="posix",
                        max_length=20,
                        verbose_name="share type",
                    ),
                ),
                (
                    "used",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Current usage in bytes. Populated by sync.",
                        null=True,
                        verbose_name="used",
                    ),
                ),
                (
                    "used_files",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Current number of files. Populated by sync.",
                        null=True,
                        verbose_name="used files",
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=50, verbose_name="state")),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_extensions",
                        to="ras.allocation",
                        unique=True,
                    ),
                ),
                (
                    "clusters",
                    models.ManyToManyField(
                        blank=True, related_name="quotas", to="storage.storagecluster", verbose_name="clusters"
                    ),
                ),
            ],
            options={
                "verbose_name": "storage quota",
                "verbose_name_plural": "storage quotas",
                "ordering": ["allocation__slug"],
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
    ]
