# Generated by Django 2.0.6 on 2018-08-03 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectuserrolechoice',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='projectuserstatuschoice',
            options={'ordering': ['name']},
        ),
    ]
