# Generated by Django 2.1 on 2018-08-29 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180829_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='force_project_review',
        ),
        migrations.RemoveField(
            model_name='project',
            name='force_project_review',
        ),
    ]
