# Generated by Django 2.1 on 2018-08-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_historicalproject_historicalprojectreview_historicalprojectreviewstatuschoice_historicalprojectuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprojectreviewstatuschoice',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalProjectReviewStatusChoice',
        ),
    ]
