# Generated by Django 2.1 on 2018-08-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180829_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='project_needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='project_needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
