# Generated by Django 2.1 on 2018-08-31 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180829_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproject',
            old_name='project_needs_review',
            new_name='force_review',
        ),
        migrations.RenameField(
            model_name='historicalproject',
            old_name='project_requires_review',
            new_name='requires_review',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_needs_review',
            new_name='force_review',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_requires_review',
            new_name='requires_review',
        ),
    ]
