# Generated by Django 2.1 on 2018-09-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_projectadmincomment_projectusercomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectadmincomment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='projectusercomment',
            old_name='user',
            new_name='author',
        ),
    ]
