# Generated by Django 3.2.13 on 2022-07-01 14:40

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('grant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grantstatuschoice',
            options={'ordering': (django.db.models.functions.text.Lower('name'),)},
        ),
    ]
