# Generated by Django 2.1.1 on 2018-09-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grant',
            options={'permissions': (('can_view_all_grants', 'Can view all grants'),), 'verbose_name_plural': 'Grants'},
        ),
    ]
