# Generated by Django 4.2.11 on 2025-01-31 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("grant", "0001_initial"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalgrant",
            name="project",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="project.project",
            ),
        ),
        migrations.AddField(
            model_name="historicalgrant",
            name="status",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="grant.grantstatuschoice",
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="funding_agency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="grant.grantfundingagency",
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="project.project"
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="grant.grantstatuschoice",
            ),
        ),
    ]
