# Generated by Django 4.2.11 on 2024-10-31 13:39

import coldfront.core.grant.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalgrant',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical grant', 'verbose_name_plural': 'historical Grants'},
        ),
        migrations.AlterField(
            model_name='grant',
            name='direct_funding',
            field=coldfront.core.grant.models.MoneyField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grant',
            name='percent_credit',
            field=coldfront.core.grant.models.PercentField(max_length=100, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='grant',
            name='total_amount_awarded',
            field=coldfront.core.grant.models.MoneyField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grantfundingagency',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='grantstatuschoice',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalgrant',
            name='direct_funding',
            field=coldfront.core.grant.models.MoneyField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalgrant',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalgrant',
            name='percent_credit',
            field=coldfront.core.grant.models.PercentField(max_length=100, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='historicalgrant',
            name='total_amount_awarded',
            field=coldfront.core.grant.models.MoneyField(max_length=100),
        ),
    ]
