# SPDX-FileCopyrightText: (C) ColdFront Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 3.2.17 on 2023-04-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grantfundingagency",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="grantstatuschoice",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
