# Generated by Django 4.2.11 on 2025-02-08 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
        ("resource", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalresource",
            name="school",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="school.school",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.school",
            ),
        ),
    ]
