# Generated by Django 2.1.7 on 2019-03-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresource',
            name='requires_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='requires_payment',
            field=models.BooleanField(default=False),
        ),
    ]
