# Generated by Django 2.2.18 on 2021-08-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20191017_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalresourceattribute',
            name='value',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resourceattribute',
            name='value',
            field=models.TextField(blank=True),
        ),
    ]
