# Generated by Django 2.2.13 on 2020-10-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20191017_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresource',
            name='is_unique_per_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_unique_per_project',
            field=models.BooleanField(default=False),
        ),
    ]
