# Generated by Django 2.2.24 on 2022-01-03 09:06

from django.db import migrations

def create_resource_types(apps, schema_editor):
    ResourceAttributeType = apps.get_model('resource', "ResourceAttributeType")
    AttributeType = apps.get_model('resource', "AttributeType")
    for resource_attribute_type, attribute_type in (
            ('Vendor', 'Text'),
            ('Model', 'Text'),
            ('RackUnits', 'Int'),
            ('InstallDate', 'Date'),
            ('WarrantyExpirationDate', 'Date'),
    ):
        ResourceAttributeType.objects.get_or_create(
                        name=resource_attribute_type, attribute_type=AttributeType.objects.get(name=attribute_type))

    ResourceType = apps.get_model('resource', "ResourceType")
    for resource_type, description in (
        ('Compute Node', 'Compute Node'),
    ):
        ResourceType.objects.get_or_create(
            name=resource_type, description=description)



class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20191017_1141'),
    ]

    operations = [
        migrations.RunPython(create_resource_types)
    ]
