# Generated by Django 3.2.14 on 2024-01-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_auto_20230518_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresource',
            name='requires_user_roles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='requires_user_roles',
            field=models.BooleanField(default=False),
        ),
    ]
