name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PLUGIN_API: True

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --dev

      - name: Check for lint violations
        run: uv run ruff check

      - name: Check formatting
        run: uv run ruff format --check

      - name: Check licence with reuse
        run: uv run reuse lint

      - name: Run tests
        run: uv run coldfront test
