name: CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "docs/**"
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
        node-version: ["24.x"]
    env:
      PLUGIN_API: true
      DJANGO_VITE_DEV_MODE: true

    steps:
      - uses: actions/checkout@v6

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install the project
        run: uv sync --locked --dev

      - name: Install frontend packages
        run: npm --prefix src/coldfront/static install

      - name: Check for lint violations
        run: uv run ruff check

      - name: Check formatting
        run: uv run ruff format --check

      - name: Check django template formatting
        run: uv run djangofmt src/coldfront

      - name: Check django template formatting have been commited
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "Error: django templates have not been formatted. Run djangofmt"
            git status
            exit 1
          else
            echo "django template formatting check passed."
          fi

      - name: Check frontend with eslint and prettier
        run: npm --prefix src/coldfront/static run check

      - name: Compile and bundle frontend static assets
        run: npm --prefix src/coldfront/static run build

      - name: Check bundled frontend static assets have been commited
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "Error: pre-compiled bundled frontend static assets have not been committed"
            git status
            exit 1
          else
            echo "Bundled frontend static assets check passed."
          fi

      - name: Check licence with reuse
        run: uv run reuse lint

      - name: Check for migrations
        run: uv run coldfront makemigrations --check

      - name: Run tests
        run: COLDFRONT_ENV=.env.testing uv run -m coverage run -m pytest

      - name: Show coverage report
        run: uv run -m coverage report --skip-covered --omit '*/migrations/*,*/tests/*'
