# Generated by Django 3.2.20 on 2023-10-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.TextField(default='True'),
            preserve_default=False,
        ),
    ]
