# Generated by Django 3.2.12 on 2022-04-08 03:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(help_text='A short code for referencing this organization.  Typically will be combined with short codes from all parents to get an unique reference. May not contain hyphen (-)', max_length=512, null=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Code field may not contain hyphen (-)', regex='-')])),
                ('shortname', models.CharField(help_text='A medium length name for this organization, used in many displays.', max_length=1024, null=True)),
                ('longname', models.CharField(help_text='The full name for this organization, for official contexts', max_length=2048, null=True)),
                ('is_selectable_for_user', models.BooleanField(default=True, help_text='This organization can be selected for Users')),
                ('is_selectable_for_project', models.BooleanField(default=True, help_text='This organization can be selected for Projects')),
            ],
            options={
                'ordering': ['organization_level', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_primary', models.BooleanField(default=False, help_text="Mark as User's 'primary' Organization.  A User can have at most one primary Organization")),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
            options={
                'ordering': ['-is_primary', 'organization__code', 'organization__pk', 'user__user__username', 'user__user__pk'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_primary', models.BooleanField(default=False, help_text="Mark as Project's 'primary' Organization.  A Project can have at most one primary Organization")),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'ordering': ['-is_primary', 'organization__code', 'organization__pk', 'project__title', 'project__pk'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='The (unique) name of the OrganizationLevel', max_length=512, null=True, unique=True)),
                ('level', models.IntegerField(help_text='The lower this value, the higher this type is in the organization.', unique=True)),
                ('export_to_xdmod', models.BooleanField(default=True, help_text='If set, this OrganizationLevel will be exported to Open XdMod')),
                ('parent', models.OneToOneField(blank=True, help_text='The parent OrganizationLevel for this OrganizationLevel, or None for the root OrganizationLevel', null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.organizationlevel')),
            ],
            options={
                'ordering': ['-level'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organizationlevel'),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='projects',
            field=models.ManyToManyField(through='organization.OrganizationProject', to='project.Project'),
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(through='organization.OrganizationUser', to='user.UserProfile'),
        ),
        migrations.CreateModel(
            name='Directory2Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('directory_string', models.CharField(max_length=1024, unique=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='organizationuser',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='organizationuser__organization_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='organizationuser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='organizationuser_user_unique_when_is_primary'),
        ),
        migrations.AddConstraint(
            model_name='organizationproject',
            constraint=models.UniqueConstraint(fields=('organization', 'project'), name='organizationproject__organization_project_unique'),
        ),
        migrations.AddConstraint(
            model_name='organizationproject',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('project',), name='organizationproject_project_unique_when_is_primary'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('code', 'parent'), name='organization_code_parent_unique'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('code',), name='organization_code_nullparent_unique'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('shortname', 'parent'), name='organization_shortname_parent_unique'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('shortname',), name='organization_shortname_nullparent_unique'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('longname', 'parent'), name='organization_longname_parent_unique'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('longname',), name='organization_longname_nullparent_unique'),
        ),
    ]
